// Generated from Silbad/iconoir-font dist/fonts/iconoir.json (Iconoir icons,
// MIT - see assets/fonts/licenses/Iconoir-LICENSE.txt). Regenerate with the
// python snippet in docs/im-touch-ui-plan.md if the font is updated.
#pragma once

#define FONT_ICON_FILE_NAME_IC "Iconoir.ttf"

#define ICON_MIN_IC 0xe000
#define ICON_MAX_IC 0xe568

#define ICON_IC_ACCESSIBILITY "\xee\x80\x80"  // U+e000 accessibility
#define ICON_IC_ACCESSIBILITY_SIGN "\xee\x80\x81"  // U+e001 accessibility-sign
#define ICON_IC_ACCESSIBILITY_TECH "\xee\x80\x82"  // U+e002 accessibility-tech
#define ICON_IC_ACTIVITY "\xee\x80\x83"  // U+e003 activity
#define ICON_IC_ADOBE_AFTER_EFFECTS "\xee\x80\x84"  // U+e004 adobe-after-effects
#define ICON_IC_ADOBE_ILLUSTRATOR "\xee\x80\x85"  // U+e005 adobe-illustrator
#define ICON_IC_ADOBE_INDESIGN "\xee\x80\x86"  // U+e006 adobe-indesign
#define ICON_IC_ADOBE_LIGHTROOM "\xee\x80\x87"  // U+e007 adobe-lightroom
#define ICON_IC_ADOBE_PHOTOSHOP "\xee\x80\x88"  // U+e008 adobe-photoshop
#define ICON_IC_ADOBE_XD "\xee\x80\x89"  // U+e009 adobe-xd
#define ICON_IC_AFRICAN_TREE "\xee\x80\x8a"  // U+e00a african-tree
#define ICON_IC_AGILE "\xee\x80\x8b"  // U+e00b agile
#define ICON_IC_AIR_CONDITIONER "\xee\x80\x8c"  // U+e00c air-conditioner
#define ICON_IC_AIRPLANE "\xee\x80\x91"  // U+e011 airplane
#define ICON_IC_AIRPLANE_HELIX "\xee\x80\x8e"  // U+e00e airplane-helix
#define ICON_IC_AIRPLANE_HELIX_45DEG "\xee\x80\x8d"  // U+e00d airplane-helix-45deg
#define ICON_IC_AIRPLANE_OFF "\xee\x80\x8f"  // U+e00f airplane-off
#define ICON_IC_AIRPLANE_ROTATION "\xee\x80\x90"  // U+e010 airplane-rotation
#define ICON_IC_AIRPLAY "\xee\x80\x92"  // U+e012 airplay
#define ICON_IC_ALARM "\xee\x80\x93"  // U+e013 alarm
#define ICON_IC_ALBUM "\xee\x80\x97"  // U+e017 album
#define ICON_IC_ALBUM_CAROUSEL "\xee\x80\x94"  // U+e014 album-carousel
#define ICON_IC_ALBUM_LIST "\xee\x80\x95"  // U+e015 album-list
#define ICON_IC_ALBUM_OPEN "\xee\x80\x96"  // U+e016 album-open
#define ICON_IC_ALIGN_BOTTOM_BOX "\xee\x80\x98"  // U+e018 align-bottom-box
#define ICON_IC_ALIGN_CENTER "\xee\x80\x99"  // U+e019 align-center
#define ICON_IC_ALIGN_HORIZONTAL_CENTERS "\xee\x80\x9a"  // U+e01a align-horizontal-centers
#define ICON_IC_ALIGN_HORIZONTAL_SPACING "\xee\x80\x9b"  // U+e01b align-horizontal-spacing
#define ICON_IC_ALIGN_JUSTIFY "\xee\x80\x9c"  // U+e01c align-justify
#define ICON_IC_ALIGN_LEFT "\xee\x80\x9e"  // U+e01e align-left
#define ICON_IC_ALIGN_LEFT_BOX "\xee\x80\x9d"  // U+e01d align-left-box
#define ICON_IC_ALIGN_RIGHT "\xee\x80\xa0"  // U+e020 align-right
#define ICON_IC_ALIGN_RIGHT_BOX "\xee\x80\x9f"  // U+e01f align-right-box
#define ICON_IC_ALIGN_TOP_BOX "\xee\x80\xa1"  // U+e021 align-top-box
#define ICON_IC_ALIGN_VERTICAL_CENTERS "\xee\x80\xa2"  // U+e022 align-vertical-centers
#define ICON_IC_ALIGN_VERTICAL_SPACING "\xee\x80\xa3"  // U+e023 align-vertical-spacing
#define ICON_IC_ANGLE_TOOL "\xee\x80\xa4"  // U+e024 angle-tool
#define ICON_IC_ANTENNA "\xee\x80\xa8"  // U+e028 antenna
#define ICON_IC_ANTENNA_OFF "\xee\x80\xa5"  // U+e025 antenna-off
#define ICON_IC_ANTENNA_SIGNAL "\xee\x80\xa7"  // U+e027 antenna-signal
#define ICON_IC_ANTENNA_SIGNAL_TAG "\xee\x80\xa6"  // U+e026 antenna-signal-tag
#define ICON_IC_APP_NOTIFICATION "\xee\x80\xa9"  // U+e029 app-notification
#define ICON_IC_APP_STORE "\xee\x80\xaa"  // U+e02a app-store
#define ICON_IC_APP_WINDOW "\xee\x80\xab"  // U+e02b app-window
#define ICON_IC_APPLE "\xee\x80\xb3"  // U+e033 apple
#define ICON_IC_APPLE_HALF "\xee\x80\xac"  // U+e02c apple-half
#define ICON_IC_APPLE_IMAC_2021 "\xee\x80\xae"  // U+e02e apple-imac-2021
#define ICON_IC_APPLE_IMAC_2021_SIDE "\xee\x80\xad"  // U+e02d apple-imac-2021-side
#define ICON_IC_APPLE_MAC "\xee\x80\xaf"  // U+e02f apple-mac
#define ICON_IC_APPLE_SHORTCUTS "\xee\x80\xb0"  // U+e030 apple-shortcuts
#define ICON_IC_APPLE_SWIFT "\xee\x80\xb1"  // U+e031 apple-swift
#define ICON_IC_APPLE_WALLET "\xee\x80\xb2"  // U+e032 apple-wallet
#define ICON_IC_AR_TAG "\xee\x80\xb4"  // U+e034 ar-tag
#define ICON_IC_ARC_3D "\xee\x80\xb6"  // U+e036 arc-3d
#define ICON_IC_ARC_3D_CENTER_POINT "\xee\x80\xb5"  // U+e035 arc-3d-center-point
#define ICON_IC_ARCADE "\xee\x80\xb7"  // U+e037 arcade
#define ICON_IC_ARCHERY "\xee\x80\xb9"  // U+e039 archery
#define ICON_IC_ARCHERY_MATCH "\xee\x80\xb8"  // U+e038 archery-match
#define ICON_IC_ARCHIVE "\xee\x80\xba"  // U+e03a archive
#define ICON_IC_AREA_SEARCH "\xee\x80\xbb"  // U+e03b area-search
#define ICON_IC_ARROW_ARCHERY "\xee\x80\xbc"  // U+e03c arrow-archery
#define ICON_IC_ARROW_DOWN "\xee\x81\x85"  // U+e045 arrow-down
#define ICON_IC_ARROW_DOWN_CIRCLE "\xee\x80\xbd"  // U+e03d arrow-down-circle
#define ICON_IC_ARROW_DOWN_LEFT "\xee\x81\x80"  // U+e040 arrow-down-left
#define ICON_IC_ARROW_DOWN_LEFT_CIRCLE "\xee\x80\xbe"  // U+e03e arrow-down-left-circle
#define ICON_IC_ARROW_DOWN_LEFT_SQUARE "\xee\x80\xbf"  // U+e03f arrow-down-left-square
#define ICON_IC_ARROW_DOWN_RIGHT "\xee\x81\x83"  // U+e043 arrow-down-right
#define ICON_IC_ARROW_DOWN_RIGHT_CIRCLE "\xee\x81\x81"  // U+e041 arrow-down-right-circle
#define ICON_IC_ARROW_DOWN_RIGHT_SQUARE "\xee\x81\x82"  // U+e042 arrow-down-right-square
#define ICON_IC_ARROW_DOWN_TAG "\xee\x81\x84"  // U+e044 arrow-down-tag
#define ICON_IC_ARROW_EMAIL_FORWARD "\xee\x81\x86"  // U+e046 arrow-email-forward
#define ICON_IC_ARROW_ENLARGE_TAG "\xee\x81\x87"  // U+e047 arrow-enlarge-tag
#define ICON_IC_ARROW_LEFT "\xee\x81\x8a"  // U+e04a arrow-left
#define ICON_IC_ARROW_LEFT_CIRCLE "\xee\x81\x88"  // U+e048 arrow-left-circle
#define ICON_IC_ARROW_LEFT_TAG "\xee\x81\x89"  // U+e049 arrow-left-tag
#define ICON_IC_ARROW_REDUCE_TAG "\xee\x81\x8b"  // U+e04b arrow-reduce-tag
#define ICON_IC_ARROW_RIGHT "\xee\x81\x8e"  // U+e04e arrow-right
#define ICON_IC_ARROW_RIGHT_CIRCLE "\xee\x81\x8c"  // U+e04c arrow-right-circle
#define ICON_IC_ARROW_RIGHT_TAG "\xee\x81\x8d"  // U+e04d arrow-right-tag
#define ICON_IC_ARROW_SEPARATE "\xee\x81\x90"  // U+e050 arrow-separate
#define ICON_IC_ARROW_SEPARATE_VERTICAL "\xee\x81\x8f"  // U+e04f arrow-separate-vertical
#define ICON_IC_ARROW_UNION "\xee\x81\x92"  // U+e052 arrow-union
#define ICON_IC_ARROW_UNION_VERTICAL "\xee\x81\x91"  // U+e051 arrow-union-vertical
#define ICON_IC_ARROW_UP "\xee\x81\x9b"  // U+e05b arrow-up
#define ICON_IC_ARROW_UP_CIRCLE "\xee\x81\x93"  // U+e053 arrow-up-circle
#define ICON_IC_ARROW_UP_LEFT "\xee\x81\x96"  // U+e056 arrow-up-left
#define ICON_IC_ARROW_UP_LEFT_CIRCLE "\xee\x81\x94"  // U+e054 arrow-up-left-circle
#define ICON_IC_ARROW_UP_LEFT_SQUARE "\xee\x81\x95"  // U+e055 arrow-up-left-square
#define ICON_IC_ARROW_UP_RIGHT "\xee\x81\x99"  // U+e059 arrow-up-right
#define ICON_IC_ARROW_UP_RIGHT_CIRCLE "\xee\x81\x97"  // U+e057 arrow-up-right-circle
#define ICON_IC_ARROW_UP_RIGHT_SQUARE "\xee\x81\x98"  // U+e058 arrow-up-right-square
#define ICON_IC_ARROW_UP_TAG "\xee\x81\x9a"  // U+e05a arrow-up-tag
#define ICON_IC_ARROWS_UP_FROM_LINE "\xee\x81\x9c"  // U+e05c arrows-up-from-line
#define ICON_IC_ASANA "\xee\x81\x9d"  // U+e05d asana
#define ICON_IC_ASTERISK "\xee\x95\x8d"  // U+e54d asterisk
#define ICON_IC_AT_SIGN "\xee\x81\x9f"  // U+e05f at-sign
#define ICON_IC_AT_SIGN_CIRCLE "\xee\x81\x9e"  // U+e05e at-sign-circle
#define ICON_IC_ATOM "\xee\x81\xa0"  // U+e060 atom
#define ICON_IC_ATTACHMENT "\xee\x81\xa1"  // U+e061 attachment
#define ICON_IC_AUGMENTED_REALITY "\xee\x81\xa2"  // U+e062 augmented-reality
#define ICON_IC_AUTO_FLASH "\xee\x81\xa3"  // U+e063 auto-flash
#define ICON_IC_AVI_FORMAT "\xee\x81\xa4"  // U+e064 avi-format
#define ICON_IC_AXES "\xee\x81\xa5"  // U+e065 axes
#define ICON_IC_BACKWARD_15_SECONDS "\xee\x81\xa6"  // U+e066 backward-15-seconds
#define ICON_IC_BADGE_CHECK "\xee\x81\xa7"  // U+e067 badge-check
#define ICON_IC_BAG "\xee\x81\xa8"  // U+e068 bag
#define ICON_IC_BALCONY "\xee\x81\xa9"  // U+e069 balcony
#define ICON_IC_BANK "\xee\x81\xaa"  // U+e06a bank
#define ICON_IC_BARCODE "\xee\x81\xab"  // U+e06b barcode
#define ICON_IC_BASKETBALL "\xee\x81\xad"  // U+e06d basketball
#define ICON_IC_BASKETBALL_FIELD "\xee\x81\xac"  // U+e06c basketball-field
#define ICON_IC_BATHROOM "\xee\x81\xae"  // U+e06e bathroom
#define ICON_IC_BATTERY_25 "\xee\x81\xaf"  // U+e06f battery-25
#define ICON_IC_BATTERY_50 "\xee\x81\xb0"  // U+e070 battery-50
#define ICON_IC_BATTERY_75 "\xee\x81\xb1"  // U+e071 battery-75
#define ICON_IC_BATTERY_CHARGING "\xee\x81\xb2"  // U+e072 battery-charging
#define ICON_IC_BATTERY_EMPTY "\xee\x81\xb3"  // U+e073 battery-empty
#define ICON_IC_BATTERY_FULL "\xee\x81\xb4"  // U+e074 battery-full
#define ICON_IC_BATTERY_INDICATOR "\xee\x81\xb5"  // U+e075 battery-indicator
#define ICON_IC_BATTERY_SLASH "\xee\x81\xb6"  // U+e076 battery-slash
#define ICON_IC_BATTERY_WARNING "\xee\x81\xb7"  // U+e077 battery-warning
#define ICON_IC_BBQ "\xee\x81\xb8"  // U+e078 bbq
#define ICON_IC_BEACH_BAG "\xee\x81\xb9"  // U+e079 beach-bag
#define ICON_IC_BED "\xee\x81\xbb"  // U+e07b bed
#define ICON_IC_BED_READY "\xee\x81\xba"  // U+e07a bed-ready
#define ICON_IC_BEHANCE "\xee\x81\xbd"  // U+e07d behance
#define ICON_IC_BEHANCE_TAG "\xee\x81\xbc"  // U+e07c behance-tag
#define ICON_IC_BELL "\xee\x82\x80"  // U+e080 bell
#define ICON_IC_BELL_NOTIFICATION "\xee\x81\xbe"  // U+e07e bell-notification
#define ICON_IC_BELL_OFF "\xee\x81\xbf"  // U+e07f bell-off
#define ICON_IC_BICYCLE "\xee\x82\x81"  // U+e081 bicycle
#define ICON_IC_BIN "\xee\x82\x86"  // U+e086 bin
#define ICON_IC_BIN_FULL "\xee\x82\x82"  // U+e082 bin-full
#define ICON_IC_BIN_HALF "\xee\x82\x83"  // U+e083 bin-half
#define ICON_IC_BIN_MINUS_IN "\xee\x82\x84"  // U+e084 bin-minus-in
#define ICON_IC_BIN_PLUS_IN "\xee\x82\x85"  // U+e085 bin-plus-in
#define ICON_IC_BINOCULAR "\xee\x82\x87"  // U+e087 binocular
#define ICON_IC_BIRTHDAY_CAKE "\xee\x82\x88"  // U+e088 birthday-cake
#define ICON_IC_BISHOP "\xee\x82\x89"  // U+e089 bishop
#define ICON_IC_BITBUCKET "\xee\x82\x8a"  // U+e08a bitbucket
#define ICON_IC_BITCOIN_CIRCLE "\xee\x82\x8b"  // U+e08b bitcoin-circle
#define ICON_IC_BITCOIN_ROTATE_OUT "\xee\x82\x8c"  // U+e08c bitcoin-rotate-out
#define ICON_IC_BLUETOOTH "\xee\x82\x8e"  // U+e08e bluetooth
#define ICON_IC_BLUETOOTH_TAG "\xee\x82\x8d"  // U+e08d bluetooth-tag
#define ICON_IC_BOLD "\xee\x82\x90"  // U+e090 bold
#define ICON_IC_BOLD_SQUARE "\xee\x82\x8f"  // U+e08f bold-square
#define ICON_IC_BONFIRE "\xee\x82\x91"  // U+e091 bonfire
#define ICON_IC_BOOK "\xee\x82\x94"  // U+e094 book
#define ICON_IC_BOOK_LOCK "\xee\x82\x92"  // U+e092 book-lock
#define ICON_IC_BOOK_STACK "\xee\x82\x93"  // U+e093 book-stack
#define ICON_IC_BOOKMARK "\xee\x82\x97"  // U+e097 bookmark
#define ICON_IC_BOOKMARK_BOOK "\xee\x82\x95"  // U+e095 bookmark-book
#define ICON_IC_BOOKMARK_CIRCLE "\xee\x82\x96"  // U+e096 bookmark-circle
#define ICON_IC_BORDER_BL "\xee\x82\x98"  // U+e098 border-bl
#define ICON_IC_BORDER_BOTTOM "\xee\x82\x99"  // U+e099 border-bottom
#define ICON_IC_BORDER_BR "\xee\x82\x9a"  // U+e09a border-br
#define ICON_IC_BORDER_INNER "\xee\x82\x9b"  // U+e09b border-inner
#define ICON_IC_BORDER_LEFT "\xee\x82\x9c"  // U+e09c border-left
#define ICON_IC_BORDER_OUT "\xee\x82\x9d"  // U+e09d border-out
#define ICON_IC_BORDER_RIGHT "\xee\x82\x9e"  // U+e09e border-right
#define ICON_IC_BORDER_TL "\xee\x82\x9f"  // U+e09f border-tl
#define ICON_IC_BORDER_TOP "\xee\x82\xa0"  // U+e0a0 border-top
#define ICON_IC_BORDER_TR "\xee\x82\xa1"  // U+e0a1 border-tr
#define ICON_IC_BOUNCE_LEFT "\xee\x82\xa2"  // U+e0a2 bounce-left
#define ICON_IC_BOUNCE_RIGHT "\xee\x82\xa3"  // U+e0a3 bounce-right
#define ICON_IC_BOWLING_BALL "\xee\x82\xa4"  // U+e0a4 bowling-ball
#define ICON_IC_BOX "\xee\x82\xa9"  // U+e0a9 box
#define ICON_IC_BOX_3D_CENTER "\xee\x82\xa5"  // U+e0a5 box-3d-center
#define ICON_IC_BOX_3D_POINT "\xee\x82\xa6"  // U+e0a6 box-3d-point
#define ICON_IC_BOX_3D_THREE_POINTS "\xee\x82\xa7"  // U+e0a7 box-3d-three-points
#define ICON_IC_BOX_ISO "\xee\x82\xa8"  // U+e0a8 box-iso
#define ICON_IC_BOXING_GLOVE "\xee\x82\xaa"  // U+e0aa boxing-glove
#define ICON_IC_BRAIN "\xee\x82\xae"  // U+e0ae brain
#define ICON_IC_BRAIN_ELECTRICITY "\xee\x82\xab"  // U+e0ab brain-electricity
#define ICON_IC_BRAIN_RESEARCH "\xee\x82\xac"  // U+e0ac brain-research
#define ICON_IC_BRAIN_WARNING "\xee\x82\xad"  // U+e0ad brain-warning
#define ICON_IC_BREAD_SLICE "\xee\x82\xaf"  // U+e0af bread-slice
#define ICON_IC_BRIDGE_3D "\xee\x82\xb0"  // U+e0b0 bridge-3d
#define ICON_IC_BRIDGE_SURFACE "\xee\x82\xb1"  // U+e0b1 bridge-surface
#define ICON_IC_BRIGHT_CROWN "\xee\x82\xb2"  // U+e0b2 bright-crown
#define ICON_IC_BRIGHT_STAR "\xee\x82\xb3"  // U+e0b3 bright-star
#define ICON_IC_BRIGHTNESS "\xee\x82\xb5"  // U+e0b5 brightness
#define ICON_IC_BRIGHTNESS_WINDOW "\xee\x82\xb4"  // U+e0b4 brightness-window
#define ICON_IC_BUBBLE_DOWNLOAD "\xee\x82\xb6"  // U+e0b6 bubble-download
#define ICON_IC_BUBBLE_INCOME "\xee\x82\xb7"  // U+e0b7 bubble-income
#define ICON_IC_BUBBLE_OUTCOME "\xee\x82\xb8"  // U+e0b8 bubble-outcome
#define ICON_IC_BUBBLE_SEARCH "\xee\x82\xb9"  // U+e0b9 bubble-search
#define ICON_IC_BUBBLE_STAR "\xee\x82\xba"  // U+e0ba bubble-star
#define ICON_IC_BUBBLE_UPLOAD "\xee\x82\xbb"  // U+e0bb bubble-upload
#define ICON_IC_BUBBLE_WARNING "\xee\x82\xbc"  // U+e0bc bubble-warning
#define ICON_IC_BUBBLE_XMARK "\xee\x82\xbd"  // U+e0bd bubble-xmark
#define ICON_IC_BUG "\xee\x95\xa5"  // U+e565 bug
#define ICON_IC_BUILDING "\xee\x82\xbe"  // U+e0be building
#define ICON_IC_BUS "\xee\x83\x81"  // U+e0c1 bus
#define ICON_IC_BUS_GREEN "\xee\x82\xbf"  // U+e0bf bus-green
#define ICON_IC_BUS_STOP "\xee\x83\x80"  // U+e0c0 bus-stop
#define ICON_IC_C_SQUARE "\xee\x83\x82"  // U+e0c2 c-square
#define ICON_IC_CABLE_TAG "\xee\x83\x83"  // U+e0c3 cable-tag
#define ICON_IC_CALCULATOR "\xee\x83\x84"  // U+e0c4 calculator
#define ICON_IC_CALENDAR "\xee\x83\x87"  // U+e0c7 calendar
#define ICON_IC_CALENDAR_ARROW_DOWN "\xee\x95\x9d"  // U+e55d calendar-arrow-down
#define ICON_IC_CALENDAR_ARROW_UP "\xee\x95\x9e"  // U+e55e calendar-arrow-up
#define ICON_IC_CALENDAR_CHECK "\xee\x95\x9f"  // U+e55f calendar-check
#define ICON_IC_CALENDAR_MINUS "\xee\x83\x85"  // U+e0c5 calendar-minus
#define ICON_IC_CALENDAR_PLUS "\xee\x83\x86"  // U+e0c6 calendar-plus
#define ICON_IC_CALENDAR_ROTATE "\xee\x95\xa0"  // U+e560 calendar-rotate
#define ICON_IC_CALENDAR_XMARK "\xee\x95\xa1"  // U+e561 calendar-xmark
#define ICON_IC_CAMERA "\xee\x83\x88"  // U+e0c8 camera
#define ICON_IC_CANDLESTICK_CHART "\xee\x83\x89"  // U+e0c9 candlestick-chart
#define ICON_IC_CAR "\xee\x83\x8a"  // U+e0ca car
#define ICON_IC_CARD_LOCK "\xee\x83\x8b"  // U+e0cb card-lock
#define ICON_IC_CARD_NO_ACCESS "\xee\x83\x8c"  // U+e0cc card-no-access
#define ICON_IC_CARD_READER "\xee\x83\x8d"  // U+e0cd card-reader
#define ICON_IC_CARD_SHIELD "\xee\x83\x8e"  // U+e0ce card-shield
#define ICON_IC_CARD_WALLET "\xee\x83\x8f"  // U+e0cf card-wallet
#define ICON_IC_CART "\xee\x83\x93"  // U+e0d3 cart
#define ICON_IC_CART_ALT "\xee\x83\x90"  // U+e0d0 cart-alt
#define ICON_IC_CART_MINUS "\xee\x83\x91"  // U+e0d1 cart-minus
#define ICON_IC_CART_PLUS "\xee\x83\x92"  // U+e0d2 cart-plus
#define ICON_IC_CASH "\xee\x83\x94"  // U+e0d4 cash
#define ICON_IC_CELL_2X2 "\xee\x83\x95"  // U+e0d5 cell-2x2
#define ICON_IC_CELLAR "\xee\x83\x96"  // U+e0d6 cellar
#define ICON_IC_CENTER_ALIGN "\xee\x83\x97"  // U+e0d7 center-align
#define ICON_IC_CHAT_BUBBLE "\xee\x83\x9e"  // U+e0de chat-bubble
#define ICON_IC_CHAT_BUBBLE_CHECK "\xee\x83\x98"  // U+e0d8 chat-bubble-check
#define ICON_IC_CHAT_BUBBLE_EMPTY "\xee\x83\x99"  // U+e0d9 chat-bubble-empty
#define ICON_IC_CHAT_BUBBLE_QUESTION "\xee\x83\x9a"  // U+e0da chat-bubble-question
#define ICON_IC_CHAT_BUBBLE_TRANSLATE "\xee\x83\x9b"  // U+e0db chat-bubble-translate
#define ICON_IC_CHAT_BUBBLE_WARNING "\xee\x83\x9c"  // U+e0dc chat-bubble-warning
#define ICON_IC_CHAT_BUBBLE_XMARK "\xee\x83\x9d"  // U+e0dd chat-bubble-xmark
#define ICON_IC_CHAT_LINES "\xee\x83\x9f"  // U+e0df chat-lines
#define ICON_IC_CHAT_MINUS_IN "\xee\x83\xa0"  // U+e0e0 chat-minus-in
#define ICON_IC_CHAT_PLUS_IN "\xee\x83\xa1"  // U+e0e1 chat-plus-in
#define ICON_IC_CHECK "\xee\x83\xa3"  // U+e0e3 check
#define ICON_IC_CHECK_CIRCLE "\xee\x83\xa2"  // U+e0e2 check-circle
#define ICON_IC_CHECK_SQUARE "\xee\x95\x99"  // U+e559 check-square
#define ICON_IC_CHOCOLATE "\xee\x83\xa4"  // U+e0e4 chocolate
#define ICON_IC_CHROMECAST "\xee\x83\xa6"  // U+e0e6 chromecast
#define ICON_IC_CHROMECAST_ACTIVE "\xee\x83\xa5"  // U+e0e5 chromecast-active
#define ICON_IC_CHURCH "\xee\x83\xa8"  // U+e0e8 church
#define ICON_IC_CHURCH_SIDE "\xee\x83\xa7"  // U+e0e7 church-side
#define ICON_IC_CIGARETTE_SLASH "\xee\x83\xa9"  // U+e0e9 cigarette-slash
#define ICON_IC_CINEMA_OLD "\xee\x83\xaa"  // U+e0ea cinema-old
#define ICON_IC_CIRCLE "\xee\x83\xac"  // U+e0ec circle
#define ICON_IC_CIRCLE_SPARK "\xee\x83\xab"  // U+e0eb circle-spark
#define ICON_IC_CITY "\xee\x83\xad"  // U+e0ed city
#define ICON_IC_CLIPBOARD_CHECK "\xee\x83\xae"  // U+e0ee clipboard-check
#define ICON_IC_CLOCK "\xee\x83\xb0"  // U+e0f0 clock
#define ICON_IC_CLOCK_ROTATE_RIGHT "\xee\x83\xaf"  // U+e0ef clock-rotate-right
#define ICON_IC_CLOSED_CAPTIONS_TAG "\xee\x83\xb1"  // U+e0f1 closed-captions-tag
#define ICON_IC_CLOSET "\xee\x83\xb2"  // U+e0f2 closet
#define ICON_IC_CLOUD "\xee\x83\xbc"  // U+e0fc cloud
#define ICON_IC_CLOUD_BOOKMARK "\xee\x83\xb3"  // U+e0f3 cloud-bookmark
#define ICON_IC_CLOUD_CHECK "\xee\x83\xb4"  // U+e0f4 cloud-check
#define ICON_IC_CLOUD_DESYNC "\xee\x83\xb5"  // U+e0f5 cloud-desync
#define ICON_IC_CLOUD_DOWNLOAD "\xee\x83\xb6"  // U+e0f6 cloud-download
#define ICON_IC_CLOUD_SQUARE "\xee\x83\xb7"  // U+e0f7 cloud-square
#define ICON_IC_CLOUD_SUNNY "\xee\x83\xb8"  // U+e0f8 cloud-sunny
#define ICON_IC_CLOUD_SYNC "\xee\x83\xb9"  // U+e0f9 cloud-sync
#define ICON_IC_CLOUD_UPLOAD "\xee\x83\xba"  // U+e0fa cloud-upload
#define ICON_IC_CLOUD_XMARK "\xee\x83\xbb"  // U+e0fb cloud-xmark
#define ICON_IC_CODE "\xee\x83\xbf"  // U+e0ff code
#define ICON_IC_CODE_BRACKETS "\xee\x83\xbe"  // U+e0fe code-brackets
#define ICON_IC_CODE_BRACKETS_SQUARE "\xee\x83\xbd"  // U+e0fd code-brackets-square
#define ICON_IC_CODEPEN "\xee\x84\x80"  // U+e100 codepen
#define ICON_IC_COFFEE_CUP "\xee\x84\x81"  // U+e101 coffee-cup
#define ICON_IC_COIN_SLASH "\xee\x84\x82"  // U+e102 coin-slash
#define ICON_IC_COINS "\xee\x84\x84"  // U+e104 coins
#define ICON_IC_COINS_SWAP "\xee\x84\x83"  // U+e103 coins-swap
#define ICON_IC_COLLAGE_FRAME "\xee\x84\x85"  // U+e105 collage-frame
#define ICON_IC_COLLAPSE "\xee\x84\x86"  // U+e106 collapse
#define ICON_IC_COLOR_FILTER "\xee\x84\x87"  // U+e107 color-filter
#define ICON_IC_COLOR_PICKER "\xee\x84\x88"  // U+e108 color-picker
#define ICON_IC_COLOR_WHEEL "\xee\x84\x89"  // U+e109 color-wheel
#define ICON_IC_COMBINE "\xee\x84\x8a"  // U+e10a combine
#define ICON_IC_COMMODITY "\xee\x84\x8b"  // U+e10b commodity
#define ICON_IC_COMMUNITY "\xee\x84\x8c"  // U+e10c community
#define ICON_IC_COMP_ALIGN_BOTTOM "\xee\x84\x8d"  // U+e10d comp-align-bottom
#define ICON_IC_COMP_ALIGN_LEFT "\xee\x84\x8e"  // U+e10e comp-align-left
#define ICON_IC_COMP_ALIGN_RIGHT "\xee\x84\x8f"  // U+e10f comp-align-right
#define ICON_IC_COMP_ALIGN_TOP "\xee\x84\x90"  // U+e110 comp-align-top
#define ICON_IC_COMPACT_DISC "\xee\x84\x91"  // U+e111 compact-disc
#define ICON_IC_COMPASS "\xee\x84\x92"  // U+e112 compass
#define ICON_IC_COMPONENT "\xee\x84\x93"  // U+e113 component
#define ICON_IC_COMPRESS "\xee\x84\x95"  // U+e115 compress
#define ICON_IC_COMPRESS_LINES "\xee\x84\x94"  // U+e114 compress-lines
#define ICON_IC_COMPUTER "\xee\x84\x96"  // U+e116 computer
#define ICON_IC_CONSTRAINED_SURFACE "\xee\x84\x97"  // U+e117 constrained-surface
#define ICON_IC_CONSUMABLE "\xee\x84\x98"  // U+e118 consumable
#define ICON_IC_CONTACTLESS "\xee\x84\x99"  // U+e119 contactless
#define ICON_IC_CONTROL_SLIDER "\xee\x84\x9a"  // U+e11a control-slider
#define ICON_IC_COOKIE "\xee\x84\x9b"  // U+e11b cookie
#define ICON_IC_COOLING_SQUARE "\xee\x84\x9c"  // U+e11c cooling-square
#define ICON_IC_COPY "\xee\x84\x9d"  // U+e11d copy
#define ICON_IC_COPYRIGHT "\xee\x84\x9e"  // U+e11e copyright
#define ICON_IC_CORNER_BOTTOM_LEFT "\xee\x84\x9f"  // U+e11f corner-bottom-left
#define ICON_IC_CORNER_BOTTOM_RIGHT "\xee\x84\xa0"  // U+e120 corner-bottom-right
#define ICON_IC_CORNER_TOP_LEFT "\xee\x84\xa1"  // U+e121 corner-top-left
#define ICON_IC_CORNER_TOP_RIGHT "\xee\x84\xa2"  // U+e122 corner-top-right
#define ICON_IC_CPU "\xee\x84\xa4"  // U+e124 cpu
#define ICON_IC_CPU_WARNING "\xee\x84\xa3"  // U+e123 cpu-warning
#define ICON_IC_CRACKED_EGG "\xee\x84\xa5"  // U+e125 cracked-egg
#define ICON_IC_CREATIVE_COMMONS "\xee\x84\xa6"  // U+e126 creative-commons
#define ICON_IC_CREDIT_CARD "\xee\x84\xa8"  // U+e128 credit-card
#define ICON_IC_CREDIT_CARD_SLASH "\xee\x84\xa7"  // U+e127 credit-card-slash
#define ICON_IC_CREDIT_CARDS "\xee\x84\xa9"  // U+e129 credit-cards
#define ICON_IC_CRIB "\xee\x84\xaa"  // U+e12a crib
#define ICON_IC_CROP "\xee\x84\xaf"  // U+e12f crop
#define ICON_IC_CROP_ROTATE_BL "\xee\x84\xab"  // U+e12b crop-rotate-bl
#define ICON_IC_CROP_ROTATE_BR "\xee\x84\xac"  // U+e12c crop-rotate-br
#define ICON_IC_CROP_ROTATE_TL "\xee\x84\xad"  // U+e12d crop-rotate-tl
#define ICON_IC_CROP_ROTATE_TR "\xee\x84\xae"  // U+e12e crop-rotate-tr
#define ICON_IC_CROWN "\xee\x84\xb1"  // U+e131 crown
#define ICON_IC_CROWN_CIRCLE "\xee\x84\xb0"  // U+e130 crown-circle
#define ICON_IC_CSS3 "\xee\x84\xb2"  // U+e132 css3
#define ICON_IC_CUBE "\xee\x84\xb7"  // U+e137 cube
#define ICON_IC_CUBE_BANDAGE "\xee\x84\xb3"  // U+e133 cube-bandage
#define ICON_IC_CUBE_CUT_WITH_CURVE "\xee\x84\xb4"  // U+e134 cube-cut-with-curve
#define ICON_IC_CUBE_DOTS "\xee\x95\xa2"  // U+e562 cube-dots
#define ICON_IC_CUBE_HOLE "\xee\x84\xb5"  // U+e135 cube-hole
#define ICON_IC_CUBE_REPLACE_FACE "\xee\x84\xb6"  // U+e136 cube-replace-face
#define ICON_IC_CUBE_SCAN "\xee\x95\xa3"  // U+e563 cube-scan
#define ICON_IC_CURSOR_POINTER "\xee\x84\xb8"  // U+e138 cursor-pointer
#define ICON_IC_CURVE_ARRAY "\xee\x84\xb9"  // U+e139 curve-array
#define ICON_IC_CUT "\xee\x84\xba"  // U+e13a cut
#define ICON_IC_CUTLERY "\xee\x84\xbb"  // U+e13b cutlery
#define ICON_IC_CYCLING "\xee\x84\xbc"  // U+e13c cycling
#define ICON_IC_CYLINDER "\xee\x84\xbd"  // U+e13d cylinder
#define ICON_IC_DASH_FLAG "\xee\x84\xbe"  // U+e13e dash-flag
#define ICON_IC_DASHBOARD "\xee\x85\x81"  // U+e141 dashboard
#define ICON_IC_DASHBOARD_DOTS "\xee\x84\xbf"  // U+e13f dashboard-dots
#define ICON_IC_DASHBOARD_SPEED "\xee\x85\x80"  // U+e140 dashboard-speed
#define ICON_IC_DATA_TRANSFER_BOTH "\xee\x85\x82"  // U+e142 data-transfer-both
#define ICON_IC_DATA_TRANSFER_CHECK "\xee\x85\x83"  // U+e143 data-transfer-check
#define ICON_IC_DATA_TRANSFER_DOWN "\xee\x85\x84"  // U+e144 data-transfer-down
#define ICON_IC_DATA_TRANSFER_UP "\xee\x85\x85"  // U+e145 data-transfer-up
#define ICON_IC_DATA_TRANSFER_WARNING "\xee\x85\x86"  // U+e146 data-transfer-warning
#define ICON_IC_DATABASE "\xee\x85\x96"  // U+e156 database
#define ICON_IC_DATABASE_BACKUP "\xee\x85\x87"  // U+e147 database-backup
#define ICON_IC_DATABASE_CHECK "\xee\x85\x88"  // U+e148 database-check
#define ICON_IC_DATABASE_EXPORT "\xee\x85\x89"  // U+e149 database-export
#define ICON_IC_DATABASE_MONITOR "\xee\x85\x8a"  // U+e14a database-monitor
#define ICON_IC_DATABASE_RESTORE "\xee\x85\x8b"  // U+e14b database-restore
#define ICON_IC_DATABASE_SCRIPT "\xee\x85\x8e"  // U+e14e database-script
#define ICON_IC_DATABASE_SCRIPT_MINUS "\xee\x85\x8c"  // U+e14c database-script-minus
#define ICON_IC_DATABASE_SCRIPT_PLUS "\xee\x85\x8d"  // U+e14d database-script-plus
#define ICON_IC_DATABASE_SEARCH "\xee\x85\x8f"  // U+e14f database-search
#define ICON_IC_DATABASE_SETTINGS "\xee\x85\x90"  // U+e150 database-settings
#define ICON_IC_DATABASE_STAR "\xee\x85\x91"  // U+e151 database-star
#define ICON_IC_DATABASE_STATS "\xee\x85\x92"  // U+e152 database-stats
#define ICON_IC_DATABASE_TAG "\xee\x85\x93"  // U+e153 database-tag
#define ICON_IC_DATABASE_WARNING "\xee\x85\x94"  // U+e154 database-warning
#define ICON_IC_DATABASE_XMARK "\xee\x85\x95"  // U+e155 database-xmark
#define ICON_IC_DE_COMPRESS "\xee\x85\x97"  // U+e157 de-compress
#define ICON_IC_DELIVERY "\xee\x85\x99"  // U+e159 delivery
#define ICON_IC_DELIVERY_TRUCK "\xee\x85\x98"  // U+e158 delivery-truck
#define ICON_IC_DEPTH "\xee\x85\x9a"  // U+e15a depth
#define ICON_IC_DESIGN_NIB "\xee\x85\x9b"  // U+e15b design-nib
#define ICON_IC_DESIGN_PENCIL "\xee\x85\x9c"  // U+e15c design-pencil
#define ICON_IC_DESK "\xee\x85\x9d"  // U+e15d desk
#define ICON_IC_DEVELOPER "\xee\x85\x9e"  // U+e15e developer
#define ICON_IC_DEW_POINT "\xee\x85\x9f"  // U+e15f dew-point
#define ICON_IC_DIALPAD "\xee\x85\xa0"  // U+e160 dialpad
#define ICON_IC_DIAMETER "\xee\x85\xa1"  // U+e161 diameter
#define ICON_IC_DICE_FIVE "\xee\x85\xa2"  // U+e162 dice-five
#define ICON_IC_DICE_FOUR "\xee\x85\xa3"  // U+e163 dice-four
#define ICON_IC_DICE_ONE "\xee\x85\xa4"  // U+e164 dice-one
#define ICON_IC_DICE_SIX "\xee\x85\xa5"  // U+e165 dice-six
#define ICON_IC_DICE_THREE "\xee\x85\xa6"  // U+e166 dice-three
#define ICON_IC_DICE_TWO "\xee\x85\xa7"  // U+e167 dice-two
#define ICON_IC_DIMMER_SWITCH "\xee\x85\xa8"  // U+e168 dimmer-switch
#define ICON_IC_DIRECTOR_CHAIR "\xee\x85\xa9"  // U+e169 director-chair
#define ICON_IC_DISCORD "\xee\x85\xaa"  // U+e16a discord
#define ICON_IC_DISHWASHER "\xee\x85\xab"  // U+e16b dishwasher
#define ICON_IC_DISPLAY_4K "\xee\x85\xac"  // U+e16c display-4k
#define ICON_IC_DIVIDE "\xee\x85\xae"  // U+e16e divide
#define ICON_IC_DIVIDE_THREE "\xee\x85\xad"  // U+e16d divide-three
#define ICON_IC_DNA "\xee\x85\xaf"  // U+e16f dna
#define ICON_IC_DNS "\xee\x95\x8e"  // U+e54e dns
#define ICON_IC_DOC_MAGNIFYING_GLASS "\xee\x85\xb1"  // U+e171 doc-magnifying-glass
#define ICON_IC_DOC_MAGNIFYING_GLASS_IN "\xee\x85\xb0"  // U+e170 doc-magnifying-glass-in
#define ICON_IC_DOC_STAR "\xee\x85\xb3"  // U+e173 doc-star
#define ICON_IC_DOC_STAR_IN "\xee\x85\xb2"  // U+e172 doc-star-in
#define ICON_IC_DOGECOIN_CIRCLE "\xee\x85\xb4"  // U+e174 dogecoin-circle
#define ICON_IC_DOGECOIN_ROTATE_OUT "\xee\x85\xb5"  // U+e175 dogecoin-rotate-out
#define ICON_IC_DOLLAR "\xee\x85\xb7"  // U+e177 dollar
#define ICON_IC_DOLLAR_CIRCLE "\xee\x85\xb6"  // U+e176 dollar-circle
#define ICON_IC_DOMOTIC_WARNING "\xee\x85\xb8"  // U+e178 domotic-warning
#define ICON_IC_DONATE "\xee\x85\xb9"  // U+e179 donate
#define ICON_IC_DOT_ARROW_DOWN "\xee\x85\xba"  // U+e17a dot-arrow-down
#define ICON_IC_DOT_ARROW_LEFT "\xee\x85\xbb"  // U+e17b dot-arrow-left
#define ICON_IC_DOT_ARROW_RIGHT "\xee\x85\xbc"  // U+e17c dot-arrow-right
#define ICON_IC_DOT_ARROW_UP "\xee\x85\xbd"  // U+e17d dot-arrow-up
#define ICON_IC_DOTS_GRID_3X3 "\xee\x95\xa6"  // U+e566 dots-grid-3x3
#define ICON_IC_DOUBLE_CHECK "\xee\x85\xbe"  // U+e17e double-check
#define ICON_IC_DOWNLOAD "\xee\x86\x82"  // U+e182 download
#define ICON_IC_DOWNLOAD_CIRCLE "\xee\x85\xbf"  // U+e17f download-circle
#define ICON_IC_DOWNLOAD_DATA_WINDOW "\xee\x86\x80"  // U+e180 download-data-window
#define ICON_IC_DOWNLOAD_SQUARE "\xee\x86\x81"  // U+e181 download-square
#define ICON_IC_DRAG "\xee\x86\x84"  // U+e184 drag
#define ICON_IC_DRAG_HAND_GESTURE "\xee\x86\x83"  // U+e183 drag-hand-gesture
#define ICON_IC_DRAWER "\xee\x86\x85"  // U+e185 drawer
#define ICON_IC_DRIBBBLE "\xee\x86\x86"  // U+e186 dribbble
#define ICON_IC_DRONE "\xee\x86\x8f"  // U+e18f drone
#define ICON_IC_DRONE_CHARGE_FULL "\xee\x86\x87"  // U+e187 drone-charge-full
#define ICON_IC_DRONE_CHARGE_HALF "\xee\x86\x88"  // U+e188 drone-charge-half
#define ICON_IC_DRONE_CHARGE_LOW "\xee\x86\x89"  // U+e189 drone-charge-low
#define ICON_IC_DRONE_CHECK "\xee\x86\x8a"  // U+e18a drone-check
#define ICON_IC_DRONE_LANDING "\xee\x86\x8b"  // U+e18b drone-landing
#define ICON_IC_DRONE_REFRESH "\xee\x86\x8c"  // U+e18c drone-refresh
#define ICON_IC_DRONE_TAKE_OFF "\xee\x86\x8d"  // U+e18d drone-take-off
#define ICON_IC_DRONE_XMARK "\xee\x86\x8e"  // U+e18e drone-xmark
#define ICON_IC_DROPLET "\xee\x86\x92"  // U+e192 droplet
#define ICON_IC_DROPLET_CHECK "\xee\x86\x90"  // U+e190 droplet-check
#define ICON_IC_DROPLET_HALF "\xee\x86\x91"  // U+e191 droplet-half
#define ICON_IC_DROPLET_SNOW_FLAKE_IN "\xee\x95\xa7"  // U+e567 droplet-snow-flake-in
#define ICON_IC_EASE_CURVE_CONTROL_POINTS "\xee\x86\x93"  // U+e193 ease-curve-control-points
#define ICON_IC_EASE_IN "\xee\x86\x96"  // U+e196 ease-in
#define ICON_IC_EASE_IN_CONTROL_POINT "\xee\x86\x94"  // U+e194 ease-in-control-point
#define ICON_IC_EASE_IN_OUT "\xee\x86\x95"  // U+e195 ease-in-out
#define ICON_IC_EASE_OUT "\xee\x86\x98"  // U+e198 ease-out
#define ICON_IC_EASE_OUT_CONTROL_POINT "\xee\x86\x97"  // U+e197 ease-out-control-point
#define ICON_IC_ECOLOGY_BOOK "\xee\x86\x99"  // U+e199 ecology-book
#define ICON_IC_EDIT "\xee\x86\x9b"  // U+e19b edit
#define ICON_IC_EDIT_PENCIL "\xee\x86\x9a"  // U+e19a edit-pencil
#define ICON_IC_EGG "\xee\x86\x9c"  // U+e19c egg
#define ICON_IC_EJECT "\xee\x86\x9d"  // U+e19d eject
#define ICON_IC_ELECTRONICS_CHIP "\xee\x86\x9e"  // U+e19e electronics-chip
#define ICON_IC_ELECTRONICS_TRANSISTOR "\xee\x86\x9f"  // U+e19f electronics-transistor
#define ICON_IC_ELEVATOR "\xee\x86\xa0"  // U+e1a0 elevator
#define ICON_IC_ELLIPSE_3D "\xee\x86\xa2"  // U+e1a2 ellipse-3d
#define ICON_IC_ELLIPSE_3D_THREE_POINTS "\xee\x86\xa1"  // U+e1a1 ellipse-3d-three-points
#define ICON_IC_EMOJI "\xee\x86\xb9"  // U+e1b9 emoji
#define ICON_IC_EMOJI_BALL "\xee\x86\xa3"  // U+e1a3 emoji-ball
#define ICON_IC_EMOJI_BLINK_LEFT "\xee\x86\xa4"  // U+e1a4 emoji-blink-left
#define ICON_IC_EMOJI_BLINK_RIGHT "\xee\x86\xa5"  // U+e1a5 emoji-blink-right
#define ICON_IC_EMOJI_LOOK_DOWN "\xee\x86\xa6"  // U+e1a6 emoji-look-down
#define ICON_IC_EMOJI_LOOK_LEFT "\xee\x86\xa7"  // U+e1a7 emoji-look-left
#define ICON_IC_EMOJI_LOOK_RIGHT "\xee\x86\xa8"  // U+e1a8 emoji-look-right
#define ICON_IC_EMOJI_LOOK_UP "\xee\x86\xa9"  // U+e1a9 emoji-look-up
#define ICON_IC_EMOJI_PUZZLED "\xee\x86\xaa"  // U+e1aa emoji-puzzled
#define ICON_IC_EMOJI_QUITE "\xee\x86\xab"  // U+e1ab emoji-quite
#define ICON_IC_EMOJI_REALLY "\xee\x86\xac"  // U+e1ac emoji-really
#define ICON_IC_EMOJI_SAD "\xee\x86\xad"  // U+e1ad emoji-sad
#define ICON_IC_EMOJI_SATISFIED "\xee\x86\xae"  // U+e1ae emoji-satisfied
#define ICON_IC_EMOJI_SING_LEFT "\xee\x86\xb0"  // U+e1b0 emoji-sing-left
#define ICON_IC_EMOJI_SING_LEFT_NOTE "\xee\x86\xaf"  // U+e1af emoji-sing-left-note
#define ICON_IC_EMOJI_SING_RIGHT "\xee\x86\xb2"  // U+e1b2 emoji-sing-right
#define ICON_IC_EMOJI_SING_RIGHT_NOTE "\xee\x86\xb1"  // U+e1b1 emoji-sing-right-note
#define ICON_IC_EMOJI_SURPRISE "\xee\x86\xb4"  // U+e1b4 emoji-surprise
#define ICON_IC_EMOJI_SURPRISE_ALT "\xee\x86\xb3"  // U+e1b3 emoji-surprise-alt
#define ICON_IC_EMOJI_TALKING_ANGRY "\xee\x86\xb5"  // U+e1b5 emoji-talking-angry
#define ICON_IC_EMOJI_TALKING_HAPPY "\xee\x86\xb6"  // U+e1b6 emoji-talking-happy
#define ICON_IC_EMOJI_THINK_LEFT "\xee\x86\xb7"  // U+e1b7 emoji-think-left
#define ICON_IC_EMOJI_THINK_RIGHT "\xee\x86\xb8"  // U+e1b8 emoji-think-right
#define ICON_IC_EMPTY_PAGE "\xee\x86\xba"  // U+e1ba empty-page
#define ICON_IC_ENERGY_USAGE_WINDOW "\xee\x86\xbb"  // U+e1bb energy-usage-window
#define ICON_IC_ENLARGE "\xee\x86\xbc"  // U+e1bc enlarge
#define ICON_IC_ERASE "\xee\x86\xbd"  // U+e1bd erase
#define ICON_IC_ETHEREUM_CIRCLE "\xee\x86\xbe"  // U+e1be ethereum-circle
#define ICON_IC_ETHEREUM_ROTATE_OUT "\xee\x86\xbf"  // U+e1bf ethereum-rotate-out
#define ICON_IC_EURO "\xee\x87\x81"  // U+e1c1 euro
#define ICON_IC_EURO_SQUARE "\xee\x87\x80"  // U+e1c0 euro-square
#define ICON_IC_EV_CHARGE "\xee\x87\x83"  // U+e1c3 ev-charge
#define ICON_IC_EV_CHARGE_ALT "\xee\x87\x82"  // U+e1c2 ev-charge-alt
#define ICON_IC_EV_PLUG "\xee\x87\x86"  // U+e1c6 ev-plug
#define ICON_IC_EV_PLUG_CHARGING "\xee\x87\x84"  // U+e1c4 ev-plug-charging
#define ICON_IC_EV_PLUG_XMARK "\xee\x87\x85"  // U+e1c5 ev-plug-xmark
#define ICON_IC_EV_STATION "\xee\x87\x87"  // U+e1c7 ev-station
#define ICON_IC_EV_TAG "\xee\x87\x88"  // U+e1c8 ev-tag
#define ICON_IC_EXCLUDE "\xee\x87\x89"  // U+e1c9 exclude
#define ICON_IC_EXPAND "\xee\x87\x8b"  // U+e1cb expand
#define ICON_IC_EXPAND_LINES "\xee\x87\x8a"  // U+e1ca expand-lines
#define ICON_IC_EXTRUDE "\xee\x87\x8c"  // U+e1cc extrude
#define ICON_IC_EYE "\xee\x87\x8e"  // U+e1ce eye
#define ICON_IC_EYE_CLOSED "\xee\x87\x8d"  // U+e1cd eye-closed
#define ICON_IC_F_SQUARE "\xee\x87\x8f"  // U+e1cf f-square
#define ICON_IC_FACE_3D_DRAFT "\xee\x87\x90"  // U+e1d0 face-3d-draft
#define ICON_IC_FACE_ID "\xee\x87\x91"  // U+e1d1 face-id
#define ICON_IC_FACEBOOK "\xee\x87\x93"  // U+e1d3 facebook
#define ICON_IC_FACEBOOK_TAG "\xee\x87\x92"  // U+e1d2 facebook-tag
#define ICON_IC_FACETIME "\xee\x87\x94"  // U+e1d4 facetime
#define ICON_IC_FARM "\xee\x87\x95"  // U+e1d5 farm
#define ICON_IC_FAST_ARROW_DOWN "\xee\x87\x97"  // U+e1d7 fast-arrow-down
#define ICON_IC_FAST_ARROW_DOWN_SQUARE "\xee\x87\x96"  // U+e1d6 fast-arrow-down-square
#define ICON_IC_FAST_ARROW_LEFT "\xee\x87\x99"  // U+e1d9 fast-arrow-left
#define ICON_IC_FAST_ARROW_LEFT_SQUARE "\xee\x87\x98"  // U+e1d8 fast-arrow-left-square
#define ICON_IC_FAST_ARROW_RIGHT "\xee\x87\x9b"  // U+e1db fast-arrow-right
#define ICON_IC_FAST_ARROW_RIGHT_SQUARE "\xee\x87\x9a"  // U+e1da fast-arrow-right-square
#define ICON_IC_FAST_ARROW_UP "\xee\x87\x9d"  // U+e1dd fast-arrow-up
#define ICON_IC_FAST_ARROW_UP_SQUARE "\xee\x87\x9c"  // U+e1dc fast-arrow-up-square
#define ICON_IC_FAST_DOWN_CIRCLE "\xee\x87\x9e"  // U+e1de fast-down-circle
#define ICON_IC_FAST_LEFT_CIRCLE "\xee\x87\x9f"  // U+e1df fast-left-circle
#define ICON_IC_FAST_RIGHT_CIRCLE "\xee\x87\xa0"  // U+e1e0 fast-right-circle
#define ICON_IC_FAST_UP_CIRCLE "\xee\x87\xa1"  // U+e1e1 fast-up-circle
#define ICON_IC_FAVOURITE_BOOK "\xee\x87\xa2"  // U+e1e2 favourite-book
#define ICON_IC_FAVOURITE_WINDOW "\xee\x87\xa3"  // U+e1e3 favourite-window
#define ICON_IC_FEMALE "\xee\x87\xa4"  // U+e1e4 female
#define ICON_IC_FIGMA "\xee\x87\xa5"  // U+e1e5 figma
#define ICON_IC_FILE_NOT_FOUND "\xee\x87\xa6"  // U+e1e6 file-not-found
#define ICON_IC_FILL_COLOR "\xee\x87\xa7"  // U+e1e7 fill-color
#define ICON_IC_FILLET_3D "\xee\x87\xa8"  // U+e1e8 fillet-3d
#define ICON_IC_FILTER "\xee\x87\xac"  // U+e1ec filter
#define ICON_IC_FILTER_ALT "\xee\x87\xa9"  // U+e1e9 filter-alt
#define ICON_IC_FILTER_LIST "\xee\x87\xab"  // U+e1eb filter-list
#define ICON_IC_FILTER_LIST_CIRCLE "\xee\x87\xaa"  // U+e1ea filter-list-circle
#define ICON_IC_FINDER "\xee\x87\xad"  // U+e1ed finder
#define ICON_IC_FINGERPRINT "\xee\x87\xb5"  // U+e1f5 fingerprint
#define ICON_IC_FINGERPRINT_CHECK_CIRCLE "\xee\x87\xae"  // U+e1ee fingerprint-check-circle
#define ICON_IC_FINGERPRINT_CIRCLE "\xee\x87\xaf"  // U+e1ef fingerprint-circle
#define ICON_IC_FINGERPRINT_LOCK_CIRCLE "\xee\x87\xb0"  // U+e1f0 fingerprint-lock-circle
#define ICON_IC_FINGERPRINT_SCAN "\xee\x87\xb1"  // U+e1f1 fingerprint-scan
#define ICON_IC_FINGERPRINT_SQUARE "\xee\x87\xb2"  // U+e1f2 fingerprint-square
#define ICON_IC_FINGERPRINT_WINDOW "\xee\x87\xb3"  // U+e1f3 fingerprint-window
#define ICON_IC_FINGERPRINT_XMARK_CIRCLE "\xee\x87\xb4"  // U+e1f4 fingerprint-xmark-circle
#define ICON_IC_FIRE_FLAME "\xee\x87\xb6"  // U+e1f6 fire-flame
#define ICON_IC_FISH "\xee\x87\xb7"  // U+e1f7 fish
#define ICON_IC_FISHING "\xee\x87\xb8"  // U+e1f8 fishing
#define ICON_IC_FLARE "\xee\x87\xb9"  // U+e1f9 flare
#define ICON_IC_FLASH "\xee\x87\xbb"  // U+e1fb flash
#define ICON_IC_FLASH_OFF "\xee\x87\xba"  // U+e1fa flash-off
#define ICON_IC_FLASK "\xee\x87\xbc"  // U+e1fc flask
#define ICON_IC_FLIP "\xee\x87\xbe"  // U+e1fe flip
#define ICON_IC_FLIP_REVERSE "\xee\x87\xbd"  // U+e1fd flip-reverse
#define ICON_IC_FLOPPY_DISK "\xee\x88\x81"  // U+e201 floppy-disk
#define ICON_IC_FLOPPY_DISK_ARROW_IN "\xee\x87\xbf"  // U+e1ff floppy-disk-arrow-in
#define ICON_IC_FLOPPY_DISK_ARROW_OUT "\xee\x88\x80"  // U+e200 floppy-disk-arrow-out
#define ICON_IC_FLOWER "\xee\x88\x82"  // U+e202 flower
#define ICON_IC_FOG "\xee\x88\x83"  // U+e203 fog
#define ICON_IC_FOLDER "\xee\x88\x88"  // U+e208 folder
#define ICON_IC_FOLDER_MINUS "\xee\x88\x84"  // U+e204 folder-minus
#define ICON_IC_FOLDER_PLUS "\xee\x88\x85"  // U+e205 folder-plus
#define ICON_IC_FOLDER_SETTINGS "\xee\x88\x86"  // U+e206 folder-settings
#define ICON_IC_FOLDER_WARNING "\xee\x88\x87"  // U+e207 folder-warning
#define ICON_IC_FONT_QUESTION "\xee\x88\x89"  // U+e209 font-question
#define ICON_IC_FOOTBALL "\xee\x88\x8b"  // U+e20b football
#define ICON_IC_FOOTBALL_BALL "\xee\x88\x8a"  // U+e20a football-ball
#define ICON_IC_FORWARD "\xee\x88\x8e"  // U+e20e forward
#define ICON_IC_FORWARD_15_SECONDS "\xee\x88\x8c"  // U+e20c forward-15-seconds
#define ICON_IC_FORWARD_MESSAGE "\xee\x88\x8d"  // U+e20d forward-message
#define ICON_IC_FRAME "\xee\x88\x96"  // U+e216 frame
#define ICON_IC_FRAME_ALT "\xee\x88\x90"  // U+e210 frame-alt
#define ICON_IC_FRAME_ALT_EMPTY "\xee\x88\x8f"  // U+e20f frame-alt-empty
#define ICON_IC_FRAME_MINUS_IN "\xee\x88\x91"  // U+e211 frame-minus-in
#define ICON_IC_FRAME_PLUS_IN "\xee\x88\x92"  // U+e212 frame-plus-in
#define ICON_IC_FRAME_SELECT "\xee\x88\x93"  // U+e213 frame-select
#define ICON_IC_FRAME_SIMPLE "\xee\x88\x94"  // U+e214 frame-simple
#define ICON_IC_FRAME_TOOL "\xee\x88\x95"  // U+e215 frame-tool
#define ICON_IC_FRIDGE "\xee\x88\x97"  // U+e217 fridge
#define ICON_IC_FX "\xee\x88\x99"  // U+e219 fx
#define ICON_IC_FX_TAG "\xee\x88\x98"  // U+e218 fx-tag
#define ICON_IC_GAMEPAD "\xee\x88\x9a"  // U+e21a gamepad
#define ICON_IC_GARAGE "\xee\x88\x9b"  // U+e21b garage
#define ICON_IC_GAS "\xee\x88\x9e"  // U+e21e gas
#define ICON_IC_GAS_TANK "\xee\x88\x9d"  // U+e21d gas-tank
#define ICON_IC_GAS_TANK_DROPLET "\xee\x88\x9c"  // U+e21c gas-tank-droplet
#define ICON_IC_GIF_FORMAT "\xee\x88\x9f"  // U+e21f gif-format
#define ICON_IC_GIFT "\xee\x88\xa0"  // U+e220 gift
#define ICON_IC_GIT "\xee\x95\x9b"  // U+e55b git
#define ICON_IC_GIT_BRANCH "\xee\x88\xa1"  // U+e221 git-branch
#define ICON_IC_GIT_CHERRY_PICK_COMMIT "\xee\x88\xa2"  // U+e222 git-cherry-pick-commit
#define ICON_IC_GIT_COMMIT "\xee\x88\xa3"  // U+e223 git-commit
#define ICON_IC_GIT_COMPARE "\xee\x88\xa4"  // U+e224 git-compare
#define ICON_IC_GIT_FORK "\xee\x88\xa5"  // U+e225 git-fork
#define ICON_IC_GIT_MERGE "\xee\x88\xa6"  // U+e226 git-merge
#define ICON_IC_GIT_PULL_REQUEST "\xee\x88\xa8"  // U+e228 git-pull-request
#define ICON_IC_GIT_PULL_REQUEST_CLOSED "\xee\x88\xa7"  // U+e227 git-pull-request-closed
#define ICON_IC_GITHUB "\xee\x88\xaa"  // U+e22a github
#define ICON_IC_GITHUB_CIRCLE "\xee\x88\xa9"  // U+e229 github-circle
#define ICON_IC_GITLAB_FULL "\xee\x88\xab"  // U+e22b gitlab-full
#define ICON_IC_GLASS_EMPTY "\xee\x88\xac"  // U+e22c glass-empty
#define ICON_IC_GLASS_FRAGILE "\xee\x88\xad"  // U+e22d glass-fragile
#define ICON_IC_GLASS_HALF "\xee\x88\xaf"  // U+e22f glass-half
#define ICON_IC_GLASS_HALF_ALT "\xee\x88\xae"  // U+e22e glass-half-alt
#define ICON_IC_GLASSES "\xee\x88\xb0"  // U+e230 glasses
#define ICON_IC_GLOBE "\xee\x88\xb1"  // U+e231 globe
#define ICON_IC_GOLF "\xee\x88\xb2"  // U+e232 golf
#define ICON_IC_GOOGLE "\xee\x88\xbb"  // U+e23b google
#define ICON_IC_GOOGLE_CIRCLE "\xee\x88\xb3"  // U+e233 google-circle
#define ICON_IC_GOOGLE_DOCS "\xee\x88\xb4"  // U+e234 google-docs
#define ICON_IC_GOOGLE_DRIVE "\xee\x88\xb8"  // U+e238 google-drive
#define ICON_IC_GOOGLE_DRIVE_CHECK "\xee\x88\xb5"  // U+e235 google-drive-check
#define ICON_IC_GOOGLE_DRIVE_SYNC "\xee\x88\xb6"  // U+e236 google-drive-sync
#define ICON_IC_GOOGLE_DRIVE_WARNING "\xee\x88\xb7"  // U+e237 google-drive-warning
#define ICON_IC_GOOGLE_HOME "\xee\x88\xb9"  // U+e239 google-home
#define ICON_IC_GOOGLE_ONE "\xee\x88\xba"  // U+e23a google-one
#define ICON_IC_GPS "\xee\x88\xbc"  // U+e23c gps
#define ICON_IC_GRADUATION_CAP "\xee\x88\xbd"  // U+e23d graduation-cap
#define ICON_IC_GRAPH_DOWN "\xee\x88\xbe"  // U+e23e graph-down
#define ICON_IC_GRAPH_UP "\xee\x88\xbf"  // U+e23f graph-up
#define ICON_IC_GRID_MINUS "\xee\x89\x80"  // U+e240 grid-minus
#define ICON_IC_GRID_PLUS "\xee\x89\x81"  // U+e241 grid-plus
#define ICON_IC_GRID_XMARK "\xee\x89\x82"  // U+e242 grid-xmark
#define ICON_IC_GROUP "\xee\x89\x83"  // U+e243 group
#define ICON_IC_GYM "\xee\x89\x84"  // U+e244 gym
#define ICON_IC_H_SQUARE "\xee\x89\x85"  // U+e245 h-square
#define ICON_IC_HALF_COOKIE "\xee\x89\x86"  // U+e246 half-cookie
#define ICON_IC_HALF_MOON "\xee\x89\x87"  // U+e247 half-moon
#define ICON_IC_HAMMER "\xee\x89\x88"  // U+e248 hammer
#define ICON_IC_HAND_BRAKE "\xee\x89\x89"  // U+e249 hand-brake
#define ICON_IC_HAND_CARD "\xee\x89\x8a"  // U+e24a hand-card
#define ICON_IC_HAND_CASH "\xee\x89\x8b"  // U+e24b hand-cash
#define ICON_IC_HAND_CONTACTLESS "\xee\x89\x8c"  // U+e24c hand-contactless
#define ICON_IC_HANDBAG "\xee\x89\x8d"  // U+e24d handbag
#define ICON_IC_HARD_DRIVE "\xee\x89\x8e"  // U+e24e hard-drive
#define ICON_IC_HASHTAG "\xee\x95\x8f"  // U+e54f hashtag
#define ICON_IC_HAT "\xee\x89\x8f"  // U+e24f hat
#define ICON_IC_HD "\xee\x89\x91"  // U+e251 hd
#define ICON_IC_HD_DISPLAY "\xee\x89\x90"  // U+e250 hd-display
#define ICON_IC_HDR "\xee\x89\x92"  // U+e252 hdr
#define ICON_IC_HEADSET "\xee\x89\x96"  // U+e256 headset
#define ICON_IC_HEADSET_BOLT "\xee\x89\x93"  // U+e253 headset-bolt
#define ICON_IC_HEADSET_HELP "\xee\x89\x94"  // U+e254 headset-help
#define ICON_IC_HEADSET_WARNING "\xee\x89\x95"  // U+e255 headset-warning
#define ICON_IC_HEALTH_SHIELD "\xee\x89\x97"  // U+e257 health-shield
#define ICON_IC_HEALTHCARE "\xee\x89\x98"  // U+e258 healthcare
#define ICON_IC_HEART "\xee\x89\x9a"  // U+e25a heart
#define ICON_IC_HEART_ARROW_DOWN "\xee\x89\x99"  // U+e259 heart-arrow-down
#define ICON_IC_HEATING_SQUARE "\xee\x89\x9b"  // U+e25b heating-square
#define ICON_IC_HEAVY_RAIN "\xee\x89\x9c"  // U+e25c heavy-rain
#define ICON_IC_HELP_CIRCLE "\xee\x89\x9d"  // U+e25d help-circle
#define ICON_IC_HELP_SQUARE "\xee\x89\x9e"  // U+e25e help-square
#define ICON_IC_HEPTAGON "\xee\x89\x9f"  // U+e25f heptagon
#define ICON_IC_HEXAGON "\xee\x89\xa2"  // U+e262 hexagon
#define ICON_IC_HEXAGON_DICE "\xee\x89\xa0"  // U+e260 hexagon-dice
#define ICON_IC_HEXAGON_PLUS "\xee\x89\xa1"  // U+e261 hexagon-plus
#define ICON_IC_HISTORIC_SHIELD "\xee\x89\xa4"  // U+e264 historic-shield
#define ICON_IC_HISTORIC_SHIELD_ALT "\xee\x89\xa3"  // U+e263 historic-shield-alt
#define ICON_IC_HOME "\xee\x89\xb2"  // U+e272 home
#define ICON_IC_HOME_ALT "\xee\x89\xa7"  // U+e267 home-alt
#define ICON_IC_HOME_ALT_SLIM "\xee\x89\xa6"  // U+e266 home-alt-slim
#define ICON_IC_HOME_ALT_SLIM_HORIZ "\xee\x89\xa5"  // U+e265 home-alt-slim-horiz
#define ICON_IC_HOME_HOSPITAL "\xee\x89\xa8"  // U+e268 home-hospital
#define ICON_IC_HOME_SALE "\xee\x89\xa9"  // U+e269 home-sale
#define ICON_IC_HOME_SECURE "\xee\x89\xaa"  // U+e26a home-secure
#define ICON_IC_HOME_SHIELD "\xee\x89\xab"  // U+e26b home-shield
#define ICON_IC_HOME_SIMPLE "\xee\x89\xad"  // U+e26d home-simple
#define ICON_IC_HOME_SIMPLE_DOOR "\xee\x89\xac"  // U+e26c home-simple-door
#define ICON_IC_HOME_TABLE "\xee\x89\xae"  // U+e26e home-table
#define ICON_IC_HOME_TEMPERATURE_IN "\xee\x89\xaf"  // U+e26f home-temperature-in
#define ICON_IC_HOME_TEMPERATURE_OUT "\xee\x89\xb0"  // U+e270 home-temperature-out
#define ICON_IC_HOME_USER "\xee\x89\xb1"  // U+e271 home-user
#define ICON_IC_HORIZ_DISTRIBUTION_LEFT "\xee\x89\xb3"  // U+e273 horiz-distribution-left
#define ICON_IC_HORIZ_DISTRIBUTION_RIGHT "\xee\x89\xb4"  // U+e274 horiz-distribution-right
#define ICON_IC_HORIZONTAL_MERGE "\xee\x89\xb5"  // U+e275 horizontal-merge
#define ICON_IC_HORIZONTAL_SPLIT "\xee\x89\xb6"  // U+e276 horizontal-split
#define ICON_IC_HOSPITAL "\xee\x89\xb8"  // U+e278 hospital
#define ICON_IC_HOSPITAL_CIRCLE "\xee\x89\xb7"  // U+e277 hospital-circle
#define ICON_IC_HOT_AIR_BALLOON "\xee\x89\xb9"  // U+e279 hot-air-balloon
#define ICON_IC_HOURGLASS "\xee\x89\xba"  // U+e27a hourglass
#define ICON_IC_HOUSE_ROOMS "\xee\x89\xbb"  // U+e27b house-rooms
#define ICON_IC_HTML5 "\xee\x89\xbc"  // U+e27c html5
#define ICON_IC_ICE_CREAM "\xee\x95\x93"  // U+e553 ice-cream
#define ICON_IC_ICONOIR "\xee\x89\xbd"  // U+e27d iconoir
#define ICON_IC_IMPORT "\xee\x89\xbe"  // U+e27e import
#define ICON_IC_INCLINATION "\xee\x89\xbf"  // U+e27f inclination
#define ICON_IC_INDUSTRY "\xee\x8a\x80"  // U+e280 industry
#define ICON_IC_INFINITE "\xee\x8a\x81"  // U+e281 infinite
#define ICON_IC_INFO_CIRCLE "\xee\x8a\x82"  // U+e282 info-circle
#define ICON_IC_INPUT_FIELD "\xee\x8a\x83"  // U+e283 input-field
#define ICON_IC_INPUT_OUTPUT "\xee\x8a\x84"  // U+e284 input-output
#define ICON_IC_INPUT_SEARCH "\xee\x8a\x85"  // U+e285 input-search
#define ICON_IC_INSTAGRAM "\xee\x8a\x86"  // U+e286 instagram
#define ICON_IC_INTERNET "\xee\x8a\x87"  // U+e287 internet
#define ICON_IC_INTERSECT "\xee\x8a\x89"  // U+e289 intersect
#define ICON_IC_INTERSECT_ALT "\xee\x8a\x88"  // U+e288 intersect-alt
#define ICON_IC_IOS_SETTINGS "\xee\x8a\x8a"  // U+e28a ios-settings
#define ICON_IC_IP_ADDRESS_TAG "\xee\x8a\x8b"  // U+e28b ip-address-tag
#define ICON_IC_IRIS_SCAN "\xee\x8a\x8c"  // U+e28c iris-scan
#define ICON_IC_ITALIC "\xee\x8a\x8e"  // U+e28e italic
#define ICON_IC_ITALIC_SQUARE "\xee\x8a\x8d"  // U+e28d italic-square
#define ICON_IC_JELLYFISH "\xee\x8a\x8f"  // U+e28f jellyfish
#define ICON_IC_JOURNAL "\xee\x8a\x91"  // U+e291 journal
#define ICON_IC_JOURNAL_PAGE "\xee\x8a\x90"  // U+e290 journal-page
#define ICON_IC_JPEG_FORMAT "\xee\x8a\x92"  // U+e292 jpeg-format
#define ICON_IC_JPG_FORMAT "\xee\x8a\x93"  // U+e293 jpg-format
#define ICON_IC_KANBAN_BOARD "\xee\x8a\x94"  // U+e294 kanban-board
#define ICON_IC_KEY "\xee\x8a\x9a"  // U+e29a key
#define ICON_IC_KEY_BACK "\xee\x8a\x95"  // U+e295 key-back
#define ICON_IC_KEY_COMMAND "\xee\x8a\x96"  // U+e296 key-command
#define ICON_IC_KEY_MINUS "\xee\x8a\x97"  // U+e297 key-minus
#define ICON_IC_KEY_PLUS "\xee\x8a\x98"  // U+e298 key-plus
#define ICON_IC_KEY_XMARK "\xee\x8a\x99"  // U+e299 key-xmark
#define ICON_IC_KEYFRAME "\xee\x8a\xa3"  // U+e2a3 keyframe
#define ICON_IC_KEYFRAME_ALIGN_CENTER "\xee\x8a\x9b"  // U+e29b keyframe-align-center
#define ICON_IC_KEYFRAME_ALIGN_HORIZONTAL "\xee\x8a\x9c"  // U+e29c keyframe-align-horizontal
#define ICON_IC_KEYFRAME_ALIGN_VERTICAL "\xee\x8a\x9d"  // U+e29d keyframe-align-vertical
#define ICON_IC_KEYFRAME_MINUS "\xee\x8a\x9f"  // U+e29f keyframe-minus
#define ICON_IC_KEYFRAME_MINUS_IN "\xee\x8a\x9e"  // U+e29e keyframe-minus-in
#define ICON_IC_KEYFRAME_PLUS "\xee\x8a\xa1"  // U+e2a1 keyframe-plus
#define ICON_IC_KEYFRAME_PLUS_IN "\xee\x8a\xa0"  // U+e2a0 keyframe-plus-in
#define ICON_IC_KEYFRAME_POSITION "\xee\x8a\xa2"  // U+e2a2 keyframe-position
#define ICON_IC_KEYFRAMES "\xee\x8a\xa7"  // U+e2a7 keyframes
#define ICON_IC_KEYFRAMES_COUPLE "\xee\x8a\xa4"  // U+e2a4 keyframes-couple
#define ICON_IC_KEYFRAMES_MINUS "\xee\x8a\xa5"  // U+e2a5 keyframes-minus
#define ICON_IC_KEYFRAMES_PLUS "\xee\x8a\xa6"  // U+e2a6 keyframes-plus
#define ICON_IC_LABEL "\xee\x8a\xa8"  // U+e2a8 label
#define ICON_IC_LAMP "\xee\x8a\xa9"  // U+e2a9 lamp
#define ICON_IC_LANGUAGE "\xee\x8a\xaa"  // U+e2aa language
#define ICON_IC_LAPTOP "\xee\x8a\xaf"  // U+e2af laptop
#define ICON_IC_LAPTOP_CHARGING "\xee\x8a\xab"  // U+e2ab laptop-charging
#define ICON_IC_LAPTOP_DEV_MODE "\xee\x8a\xac"  // U+e2ac laptop-dev-mode
#define ICON_IC_LAPTOP_FIX "\xee\x8a\xad"  // U+e2ad laptop-fix
#define ICON_IC_LAPTOP_WARNING "\xee\x8a\xae"  // U+e2ae laptop-warning
#define ICON_IC_LAYOUT_LEFT "\xee\x8a\xb0"  // U+e2b0 layout-left
#define ICON_IC_LAYOUT_RIGHT "\xee\x8a\xb1"  // U+e2b1 layout-right
#define ICON_IC_LEADERBOARD "\xee\x8a\xb3"  // U+e2b3 leaderboard
#define ICON_IC_LEADERBOARD_STAR "\xee\x8a\xb2"  // U+e2b2 leaderboard-star
#define ICON_IC_LEAF "\xee\x8a\xb4"  // U+e2b4 leaf
#define ICON_IC_LEARNING "\xee\x8a\xb5"  // U+e2b5 learning
#define ICON_IC_LENS "\xee\x8a\xb7"  // U+e2b7 lens
#define ICON_IC_LENS_PLUS "\xee\x8a\xb6"  // U+e2b6 lens-plus
#define ICON_IC_LIFEBELT "\xee\x8a\xb8"  // U+e2b8 lifebelt
#define ICON_IC_LIGHT_BULB "\xee\x8a\xbb"  // U+e2bb light-bulb
#define ICON_IC_LIGHT_BULB_OFF "\xee\x8a\xb9"  // U+e2b9 light-bulb-off
#define ICON_IC_LIGHT_BULB_ON "\xee\x8a\xba"  // U+e2ba light-bulb-on
#define ICON_IC_LINE_SPACE "\xee\x8a\xbc"  // U+e2bc line-space
#define ICON_IC_LINEAR "\xee\x8a\xbd"  // U+e2bd linear
#define ICON_IC_LINK "\xee\x8b\x80"  // U+e2c0 link
#define ICON_IC_LINK_SLASH "\xee\x8a\xbe"  // U+e2be link-slash
#define ICON_IC_LINK_XMARK "\xee\x8a\xbf"  // U+e2bf link-xmark
#define ICON_IC_LINKEDIN "\xee\x8b\x81"  // U+e2c1 linkedin
#define ICON_IC_LINUX "\xee\x8b\x82"  // U+e2c2 linux
#define ICON_IC_LIST "\xee\x8b\x84"  // U+e2c4 list
#define ICON_IC_LIST_SELECT "\xee\x8b\x83"  // U+e2c3 list-select
#define ICON_IC_LITECOIN_CIRCLE "\xee\x8b\x85"  // U+e2c5 litecoin-circle
#define ICON_IC_LITECOIN_ROTATE_OUT "\xee\x8b\x86"  // U+e2c6 litecoin-rotate-out
#define ICON_IC_LOCK "\xee\x8b\x89"  // U+e2c9 lock
#define ICON_IC_LOCK_SLASH "\xee\x8b\x87"  // U+e2c7 lock-slash
#define ICON_IC_LOCK_SQUARE "\xee\x8b\x88"  // U+e2c8 lock-square
#define ICON_IC_LOFT_3D "\xee\x8b\x8a"  // U+e2ca loft-3d
#define ICON_IC_LOG_IN "\xee\x8b\x8b"  // U+e2cb log-in
#define ICON_IC_LOG_NO_ACCESS "\xee\x8b\x8c"  // U+e2cc log-no-access
#define ICON_IC_LOG_OUT "\xee\x8b\x8d"  // U+e2cd log-out
#define ICON_IC_LONG_ARROW_DOWN_LEFT "\xee\x8b\x8e"  // U+e2ce long-arrow-down-left
#define ICON_IC_LONG_ARROW_DOWN_RIGHT "\xee\x8b\x8f"  // U+e2cf long-arrow-down-right
#define ICON_IC_LONG_ARROW_LEFT_DOWN "\xee\x8b\x90"  // U+e2d0 long-arrow-left-down
#define ICON_IC_LONG_ARROW_LEFT_UP "\xee\x8b\x91"  // U+e2d1 long-arrow-left-up
#define ICON_IC_LONG_ARROW_RIGHT_DOWN "\xee\x8b\x92"  // U+e2d2 long-arrow-right-down
#define ICON_IC_LONG_ARROW_RIGHT_UP "\xee\x8b\x93"  // U+e2d3 long-arrow-right-up
#define ICON_IC_LONG_ARROW_UP_LEFT "\xee\x8b\x94"  // U+e2d4 long-arrow-up-left
#define ICON_IC_LONG_ARROW_UP_RIGHT "\xee\x8b\x95"  // U+e2d5 long-arrow-up-right
#define ICON_IC_LOT_OF_CASH "\xee\x8b\x96"  // U+e2d6 lot-of-cash
#define ICON_IC_LULLABY "\xee\x8b\x97"  // U+e2d7 lullaby
#define ICON_IC_MAC_CONTROL_KEY "\xee\x8b\x98"  // U+e2d8 mac-control-key
#define ICON_IC_MAC_DOCK "\xee\x8b\x99"  // U+e2d9 mac-dock
#define ICON_IC_MAC_OPTION_KEY "\xee\x8b\x9a"  // U+e2da mac-option-key
#define ICON_IC_MAC_OS_WINDOW "\xee\x8b\x9b"  // U+e2db mac-os-window
#define ICON_IC_MAGIC_WAND "\xee\x8b\x9c"  // U+e2dc magic-wand
#define ICON_IC_MAGNET "\xee\x8b\x9e"  // U+e2de magnet
#define ICON_IC_MAGNET_ENERGY "\xee\x8b\x9d"  // U+e2dd magnet-energy
#define ICON_IC_MAIL "\xee\x8b\xa2"  // U+e2e2 mail
#define ICON_IC_MAIL_IN "\xee\x8b\x9f"  // U+e2df mail-in
#define ICON_IC_MAIL_OPEN "\xee\x8b\xa0"  // U+e2e0 mail-open
#define ICON_IC_MAIL_OUT "\xee\x8b\xa1"  // U+e2e1 mail-out
#define ICON_IC_MALE "\xee\x8b\xa3"  // U+e2e3 male
#define ICON_IC_MAP "\xee\x8b\xa9"  // U+e2e9 map
#define ICON_IC_MAP_PIN "\xee\x8b\xa7"  // U+e2e7 map-pin
#define ICON_IC_MAP_PIN_MINUS "\xee\x8b\xa4"  // U+e2e4 map-pin-minus
#define ICON_IC_MAP_PIN_PLUS "\xee\x8b\xa5"  // U+e2e5 map-pin-plus
#define ICON_IC_MAP_PIN_XMARK "\xee\x8b\xa6"  // U+e2e6 map-pin-xmark
#define ICON_IC_MAP_XMARK "\xee\x8b\xa8"  // U+e2e8 map-xmark
#define ICON_IC_MAPS_ARROW "\xee\x8b\xac"  // U+e2ec maps-arrow
#define ICON_IC_MAPS_ARROW_DIAGONAL "\xee\x8b\xaa"  // U+e2ea maps-arrow-diagonal
#define ICON_IC_MAPS_ARROW_XMARK "\xee\x8b\xab"  // U+e2eb maps-arrow-xmark
#define ICON_IC_MAPS_GO_STRAIGHT "\xee\x8b\xad"  // U+e2ed maps-go-straight
#define ICON_IC_MAPS_TURN_BACK "\xee\x8b\xae"  // U+e2ee maps-turn-back
#define ICON_IC_MAPS_TURN_LEFT "\xee\x8b\xaf"  // U+e2ef maps-turn-left
#define ICON_IC_MAPS_TURN_RIGHT "\xee\x8b\xb0"  // U+e2f0 maps-turn-right
#define ICON_IC_MASK_SQUARE "\xee\x8b\xb1"  // U+e2f1 mask-square
#define ICON_IC_MASTERCARD_CARD "\xee\x8b\xb2"  // U+e2f2 mastercard-card
#define ICON_IC_MASTODON "\xee\x95\x94"  // U+e554 mastodon
#define ICON_IC_MATH_BOOK "\xee\x8b\xb3"  // U+e2f3 math-book
#define ICON_IC_MAXIMIZE "\xee\x8b\xb4"  // U+e2f4 maximize
#define ICON_IC_MEDAL "\xee\x8b\xb6"  // U+e2f6 medal
#define ICON_IC_MEDAL_1ST "\xee\x8b\xb5"  // U+e2f5 medal-1st
#define ICON_IC_MEDIA_IMAGE "\xee\x8b\xbb"  // U+e2fb media-image
#define ICON_IC_MEDIA_IMAGE_FOLDER "\xee\x8b\xb7"  // U+e2f7 media-image-folder
#define ICON_IC_MEDIA_IMAGE_LIST "\xee\x8b\xb8"  // U+e2f8 media-image-list
#define ICON_IC_MEDIA_IMAGE_PLUS "\xee\x8b\xb9"  // U+e2f9 media-image-plus
#define ICON_IC_MEDIA_IMAGE_XMARK "\xee\x8b\xba"  // U+e2fa media-image-xmark
#define ICON_IC_MEDIA_VIDEO "\xee\x8c\x80"  // U+e300 media-video
#define ICON_IC_MEDIA_VIDEO_FOLDER "\xee\x8b\xbc"  // U+e2fc media-video-folder
#define ICON_IC_MEDIA_VIDEO_LIST "\xee\x8b\xbd"  // U+e2fd media-video-list
#define ICON_IC_MEDIA_VIDEO_PLUS "\xee\x8b\xbe"  // U+e2fe media-video-plus
#define ICON_IC_MEDIA_VIDEO_XMARK "\xee\x8b\xbf"  // U+e2ff media-video-xmark
#define ICON_IC_MEDIUM "\xee\x8c\x81"  // U+e301 medium
#define ICON_IC_MEGAPHONE "\xee\x8c\x82"  // U+e302 megaphone
#define ICON_IC_MENU "\xee\x8c\x84"  // U+e304 menu
#define ICON_IC_MENU_SCALE "\xee\x8c\x83"  // U+e303 menu-scale
#define ICON_IC_MESSAGE "\xee\x8c\x87"  // U+e307 message
#define ICON_IC_MESSAGE_ALERT "\xee\x8c\x85"  // U+e305 message-alert
#define ICON_IC_MESSAGE_TEXT "\xee\x8c\x86"  // U+e306 message-text
#define ICON_IC_METER_ARROW_DOWN_RIGHT "\xee\x95\x95"  // U+e555 meter-arrow-down-right
#define ICON_IC_METRO "\xee\x8c\x88"  // U+e308 metro
#define ICON_IC_MICROPHONE "\xee\x8c\x8f"  // U+e30f microphone
#define ICON_IC_MICROPHONE_CHECK "\xee\x8c\x89"  // U+e309 microphone-check
#define ICON_IC_MICROPHONE_MINUS "\xee\x8c\x8a"  // U+e30a microphone-minus
#define ICON_IC_MICROPHONE_MUTE "\xee\x8c\x8b"  // U+e30b microphone-mute
#define ICON_IC_MICROPHONE_PLUS "\xee\x8c\x8c"  // U+e30c microphone-plus
#define ICON_IC_MICROPHONE_SPEAKING "\xee\x8c\x8d"  // U+e30d microphone-speaking
#define ICON_IC_MICROPHONE_WARNING "\xee\x8c\x8e"  // U+e30e microphone-warning
#define ICON_IC_MICROSCOPE "\xee\x8c\x90"  // U+e310 microscope
#define ICON_IC_MINUS "\xee\x8c\x95"  // U+e315 minus
#define ICON_IC_MINUS_CIRCLE "\xee\x8c\x91"  // U+e311 minus-circle
#define ICON_IC_MINUS_HEXAGON "\xee\x8c\x92"  // U+e312 minus-hexagon
#define ICON_IC_MINUS_SQUARE "\xee\x8c\x94"  // U+e314 minus-square
#define ICON_IC_MINUS_SQUARE_DASHED "\xee\x8c\x93"  // U+e313 minus-square-dashed
#define ICON_IC_MIRROR "\xee\x8c\x96"  // U+e316 mirror
#define ICON_IC_MOBILE_DEV_MODE "\xee\x8c\x97"  // U+e317 mobile-dev-mode
#define ICON_IC_MOBILE_FINGERPRINT "\xee\x8c\x98"  // U+e318 mobile-fingerprint
#define ICON_IC_MOBILE_VOICE "\xee\x8c\x99"  // U+e319 mobile-voice
#define ICON_IC_MODERN_TV "\xee\x8c\x9b"  // U+e31b modern-tv
#define ICON_IC_MODERN_TV_4K "\xee\x8c\x9a"  // U+e31a modern-tv-4k
#define ICON_IC_MONEY_SQUARE "\xee\x8c\x9c"  // U+e31c money-square
#define ICON_IC_MOON_SAT "\xee\x8c\x9d"  // U+e31d moon-sat
#define ICON_IC_MORE_HORIZ "\xee\x8c\x9f"  // U+e31f more-horiz
#define ICON_IC_MORE_HORIZ_CIRCLE "\xee\x8c\x9e"  // U+e31e more-horiz-circle
#define ICON_IC_MORE_VERT "\xee\x8c\xa1"  // U+e321 more-vert
#define ICON_IC_MORE_VERT_CIRCLE "\xee\x8c\xa0"  // U+e320 more-vert-circle
#define ICON_IC_MOTORCYCLE "\xee\x8c\xa2"  // U+e322 motorcycle
#define ICON_IC_MOUSE_BUTTON_LEFT "\xee\x8c\xa3"  // U+e323 mouse-button-left
#define ICON_IC_MOUSE_BUTTON_RIGHT "\xee\x8c\xa4"  // U+e324 mouse-button-right
#define ICON_IC_MOUSE_SCROLL_WHEEL "\xee\x8c\xa5"  // U+e325 mouse-scroll-wheel
#define ICON_IC_MOVIE "\xee\x8c\xa6"  // U+e326 movie
#define ICON_IC_MPEG_FORMAT "\xee\x8c\xa7"  // U+e327 mpeg-format
#define ICON_IC_MULTI_BUBBLE "\xee\x8c\xa8"  // U+e328 multi-bubble
#define ICON_IC_MULTI_MAC_OS_WINDOW "\xee\x8c\xa9"  // U+e329 multi-mac-os-window
#define ICON_IC_MULTI_WINDOW "\xee\x8c\xaa"  // U+e32a multi-window
#define ICON_IC_MULTIPLE_PAGES "\xee\x8c\xaf"  // U+e32f multiple-pages
#define ICON_IC_MULTIPLE_PAGES_EMPTY "\xee\x8c\xab"  // U+e32b multiple-pages-empty
#define ICON_IC_MULTIPLE_PAGES_MINUS "\xee\x8c\xac"  // U+e32c multiple-pages-minus
#define ICON_IC_MULTIPLE_PAGES_PLUS "\xee\x8c\xad"  // U+e32d multiple-pages-plus
#define ICON_IC_MULTIPLE_PAGES_XMARK "\xee\x8c\xae"  // U+e32e multiple-pages-xmark
#define ICON_IC_MUSIC_DOUBLE_NOTE "\xee\x8c\xb1"  // U+e331 music-double-note
#define ICON_IC_MUSIC_DOUBLE_NOTE_PLUS "\xee\x8c\xb0"  // U+e330 music-double-note-plus
#define ICON_IC_MUSIC_NOTE "\xee\x8c\xb3"  // U+e333 music-note
#define ICON_IC_MUSIC_NOTE_PLUS "\xee\x8c\xb2"  // U+e332 music-note-plus
#define ICON_IC_N_SQUARE "\xee\x8c\xb4"  // U+e334 n-square
#define ICON_IC_NAV_ARROW_DOWN "\xee\x8c\xb5"  // U+e335 nav-arrow-down
#define ICON_IC_NAV_ARROW_LEFT "\xee\x8c\xb6"  // U+e336 nav-arrow-left
#define ICON_IC_NAV_ARROW_RIGHT "\xee\x8c\xb7"  // U+e337 nav-arrow-right
#define ICON_IC_NAV_ARROW_UP "\xee\x8c\xb8"  // U+e338 nav-arrow-up
#define ICON_IC_NAVIGATOR "\xee\x8c\xba"  // U+e33a navigator
#define ICON_IC_NAVIGATOR_ALT "\xee\x8c\xb9"  // U+e339 navigator-alt
#define ICON_IC_NEIGHBOURHOOD "\xee\x8c\xbb"  // U+e33b neighbourhood
#define ICON_IC_NETWORK "\xee\x8c\xbf"  // U+e33f network
#define ICON_IC_NETWORK_LEFT "\xee\x8c\xbc"  // U+e33c network-left
#define ICON_IC_NETWORK_REVERSE "\xee\x8c\xbd"  // U+e33d network-reverse
#define ICON_IC_NETWORK_RIGHT "\xee\x8c\xbe"  // U+e33e network-right
#define ICON_IC_NEW_TAB "\xee\x8d\x80"  // U+e340 new-tab
#define ICON_IC_NINTENDO_SWITCH "\xee\x8d\x81"  // U+e341 nintendo-switch
#define ICON_IC_NO_SMOKING_CIRCLE "\xee\x8d\x82"  // U+e342 no-smoking-circle
#define ICON_IC_NON_BINARY "\xee\x8d\x83"  // U+e343 non-binary
#define ICON_IC_NOTES "\xee\x8d\x84"  // U+e344 notes
#define ICON_IC_NPM "\xee\x8d\x86"  // U+e346 npm
#define ICON_IC_NPM_SQUARE "\xee\x8d\x85"  // U+e345 npm-square
#define ICON_IC_NUMBER_0_SQUARE "\xee\x8d\x87"  // U+e347 number-0-square
#define ICON_IC_NUMBER_1_SQUARE "\xee\x8d\x88"  // U+e348 number-1-square
#define ICON_IC_NUMBER_2_SQUARE "\xee\x8d\x89"  // U+e349 number-2-square
#define ICON_IC_NUMBER_3_SQUARE "\xee\x8d\x8a"  // U+e34a number-3-square
#define ICON_IC_NUMBER_4_SQUARE "\xee\x8d\x8b"  // U+e34b number-4-square
#define ICON_IC_NUMBER_5_SQUARE "\xee\x8d\x8c"  // U+e34c number-5-square
#define ICON_IC_NUMBER_6_SQUARE "\xee\x8d\x8d"  // U+e34d number-6-square
#define ICON_IC_NUMBER_7_SQUARE "\xee\x8d\x8e"  // U+e34e number-7-square
#define ICON_IC_NUMBER_8_SQUARE "\xee\x8d\x8f"  // U+e34f number-8-square
#define ICON_IC_NUMBER_9_SQUARE "\xee\x8d\x90"  // U+e350 number-9-square
#define ICON_IC_NUMBERED_LIST_LEFT "\xee\x8d\x91"  // U+e351 numbered-list-left
#define ICON_IC_NUMBERED_LIST_RIGHT "\xee\x8d\x92"  // U+e352 numbered-list-right
#define ICON_IC_O_SQUARE "\xee\x8d\x93"  // U+e353 o-square
#define ICON_IC_OCTAGON "\xee\x8d\x94"  // U+e354 octagon
#define ICON_IC_OFF_TAG "\xee\x8d\x95"  // U+e355 off-tag
#define ICON_IC_OIL_INDUSTRY "\xee\x8d\x96"  // U+e356 oil-industry
#define ICON_IC_OKRS "\xee\x8d\x97"  // U+e357 okrs
#define ICON_IC_ON_TAG "\xee\x8d\x98"  // U+e358 on-tag
#define ICON_IC_ONE_FINGER_SELECT_HAND_GESTURE "\xee\x8d\x99"  // U+e359 one-finger-select-hand-gesture
#define ICON_IC_ONE_POINT_CIRCLE "\xee\x8d\x9a"  // U+e35a one-point-circle
#define ICON_IC_OPEN_BOOK "\xee\x8d\x9b"  // U+e35b open-book
#define ICON_IC_OPEN_IN_BROWSER "\xee\x8d\x9c"  // U+e35c open-in-browser
#define ICON_IC_OPEN_IN_WINDOW "\xee\x8d\x9d"  // U+e35d open-in-window
#define ICON_IC_OPEN_NEW_WINDOW "\xee\x8d\x9e"  // U+e35e open-new-window
#define ICON_IC_OPEN_SELECT_HAND_GESTURE "\xee\x8d\x9f"  // U+e35f open-select-hand-gesture
#define ICON_IC_OPEN_VPN "\xee\x8d\xa0"  // U+e360 open-vpn
#define ICON_IC_ORANGE_HALF "\xee\x8d\xa1"  // U+e361 orange-half
#define ICON_IC_ORANGE_SLICE "\xee\x8d\xa3"  // U+e363 orange-slice
#define ICON_IC_ORANGE_SLICE_ALT "\xee\x8d\xa2"  // U+e362 orange-slice-alt
#define ICON_IC_ORGANIC_FOOD "\xee\x8d\xa5"  // U+e365 organic-food
#define ICON_IC_ORGANIC_FOOD_SQUARE "\xee\x8d\xa4"  // U+e364 organic-food-square
#define ICON_IC_ORTHOGONAL_VIEW "\xee\x8d\xa6"  // U+e366 orthogonal-view
#define ICON_IC_PACKAGE "\xee\x8d\xa8"  // U+e368 package
#define ICON_IC_PACKAGE_LOCK "\xee\x8d\xa7"  // U+e367 package-lock
#define ICON_IC_PACKAGES "\xee\x8d\xa9"  // U+e369 packages
#define ICON_IC_PACMAN "\xee\x8d\xaa"  // U+e36a pacman
#define ICON_IC_PAGE "\xee\x8d\xb7"  // U+e377 page
#define ICON_IC_PAGE_DOWN "\xee\x8d\xab"  // U+e36b page-down
#define ICON_IC_PAGE_EDIT "\xee\x8d\xac"  // U+e36c page-edit
#define ICON_IC_PAGE_FLIP "\xee\x8d\xad"  // U+e36d page-flip
#define ICON_IC_PAGE_LEFT "\xee\x8d\xae"  // U+e36e page-left
#define ICON_IC_PAGE_MINUS "\xee\x8d\xb0"  // U+e370 page-minus
#define ICON_IC_PAGE_MINUS_IN "\xee\x8d\xaf"  // U+e36f page-minus-in
#define ICON_IC_PAGE_PLUS "\xee\x8d\xb2"  // U+e372 page-plus
#define ICON_IC_PAGE_PLUS_IN "\xee\x8d\xb1"  // U+e371 page-plus-in
#define ICON_IC_PAGE_RIGHT "\xee\x8d\xb3"  // U+e373 page-right
#define ICON_IC_PAGE_SEARCH "\xee\x8d\xb4"  // U+e374 page-search
#define ICON_IC_PAGE_STAR "\xee\x8d\xb5"  // U+e375 page-star
#define ICON_IC_PAGE_UP "\xee\x8d\xb6"  // U+e376 page-up
#define ICON_IC_PALETTE "\xee\x8d\xb8"  // U+e378 palette
#define ICON_IC_PANORAMA_ENLARGE "\xee\x8d\xb9"  // U+e379 panorama-enlarge
#define ICON_IC_PANORAMA_REDUCE "\xee\x8d\xba"  // U+e37a panorama-reduce
#define ICON_IC_PANTS "\xee\x8d\xbc"  // U+e37c pants
#define ICON_IC_PANTS_POCKETS "\xee\x8d\xbb"  // U+e37b pants-pockets
#define ICON_IC_PARKING "\xee\x8d\xbd"  // U+e37d parking
#define ICON_IC_PASSWORD_CHECK "\xee\x8d\xbe"  // U+e37e password-check
#define ICON_IC_PASSWORD_CURSOR "\xee\x8d\xbf"  // U+e37f password-cursor
#define ICON_IC_PASSWORD_XMARK "\xee\x8e\x80"  // U+e380 password-xmark
#define ICON_IC_PASTE_CLIPBOARD "\xee\x8e\x81"  // U+e381 paste-clipboard
#define ICON_IC_PATH_ARROW "\xee\x8e\x82"  // U+e382 path-arrow
#define ICON_IC_PAUSE "\xee\x8e\x84"  // U+e384 pause
#define ICON_IC_PAUSE_WINDOW "\xee\x8e\x83"  // U+e383 pause-window
#define ICON_IC_PAYPAL "\xee\x8e\x85"  // U+e385 paypal
#define ICON_IC_PC_CHECK "\xee\x8e\x86"  // U+e386 pc-check
#define ICON_IC_PC_FIREWALL "\xee\x8e\x87"  // U+e387 pc-firewall
#define ICON_IC_PC_MOUSE "\xee\x8e\x88"  // U+e388 pc-mouse
#define ICON_IC_PC_NO_ENTRY "\xee\x8e\x89"  // U+e389 pc-no-entry
#define ICON_IC_PC_WARNING "\xee\x8e\x8a"  // U+e38a pc-warning
#define ICON_IC_PEACE_HAND "\xee\x8e\x8b"  // U+e38b peace-hand
#define ICON_IC_PEERLIST "\xee\x95\x90"  // U+e550 peerlist
#define ICON_IC_PEN_CONNECT_BLUETOOTH "\xee\x8e\x8c"  // U+e38c pen-connect-bluetooth
#define ICON_IC_PEN_CONNECT_WIFI "\xee\x8e\x8d"  // U+e38d pen-connect-wifi
#define ICON_IC_PEN_TABLET "\xee\x8e\x90"  // U+e390 pen-tablet
#define ICON_IC_PEN_TABLET_CONNECT_USB "\xee\x8e\x8e"  // U+e38e pen-tablet-connect-usb
#define ICON_IC_PEN_TABLET_CONNECT_WIFI "\xee\x8e\x8f"  // U+e38f pen-tablet-connect-wifi
#define ICON_IC_PENTAGON "\xee\x8e\x91"  // U+e391 pentagon
#define ICON_IC_PEOPLE_TAG "\xee\x8e\x92"  // U+e392 people-tag
#define ICON_IC_PERCENT_ROTATE_OUT "\xee\x8e\x93"  // U+e393 percent-rotate-out
#define ICON_IC_PERCENTAGE "\xee\x8e\x96"  // U+e396 percentage
#define ICON_IC_PERCENTAGE_CIRCLE "\xee\x8e\x94"  // U+e394 percentage-circle
#define ICON_IC_PERCENTAGE_SQUARE "\xee\x8e\x95"  // U+e395 percentage-square
#define ICON_IC_PERSPECTIVE_VIEW "\xee\x8e\x97"  // U+e397 perspective-view
#define ICON_IC_PHARMACY_CROSS_CIRCLE "\xee\x8e\x98"  // U+e398 pharmacy-cross-circle
#define ICON_IC_PHARMACY_CROSS_TAG "\xee\x8e\x99"  // U+e399 pharmacy-cross-tag
#define ICON_IC_PHONE "\xee\x8e\xa1"  // U+e3a1 phone
#define ICON_IC_PHONE_DISABLED "\xee\x8e\x9a"  // U+e39a phone-disabled
#define ICON_IC_PHONE_INCOME "\xee\x8e\x9b"  // U+e39b phone-income
#define ICON_IC_PHONE_MINUS "\xee\x8e\x9c"  // U+e39c phone-minus
#define ICON_IC_PHONE_OUTCOME "\xee\x8e\x9d"  // U+e39d phone-outcome
#define ICON_IC_PHONE_PAUSED "\xee\x8e\x9e"  // U+e39e phone-paused
#define ICON_IC_PHONE_PLUS "\xee\x8e\x9f"  // U+e39f phone-plus
#define ICON_IC_PHONE_XMARK "\xee\x8e\xa0"  // U+e3a0 phone-xmark
#define ICON_IC_PIGGY_BANK "\xee\x8e\xa2"  // U+e3a2 piggy-bank
#define ICON_IC_PILLOW "\xee\x8e\xa3"  // U+e3a3 pillow
#define ICON_IC_PIN "\xee\x8e\xa5"  // U+e3a5 pin
#define ICON_IC_PIN_SLASH "\xee\x8e\xa4"  // U+e3a4 pin-slash
#define ICON_IC_PINE_TREE "\xee\x8e\xa6"  // U+e3a6 pine-tree
#define ICON_IC_PINTEREST "\xee\x8e\xa7"  // U+e3a7 pinterest
#define ICON_IC_PIPE_3D "\xee\x8e\xa8"  // U+e3a8 pipe-3d
#define ICON_IC_PIZZA_SLICE "\xee\x8e\xa9"  // U+e3a9 pizza-slice
#define ICON_IC_PLANET "\xee\x8e\xac"  // U+e3ac planet
#define ICON_IC_PLANET_ALT "\xee\x8e\xaa"  // U+e3aa planet-alt
#define ICON_IC_PLANET_SAT "\xee\x8e\xab"  // U+e3ab planet-sat
#define ICON_IC_PLANIMETRY "\xee\x8e\xad"  // U+e3ad planimetry
#define ICON_IC_PLAY "\xee\x8e\xae"  // U+e3ae play
#define ICON_IC_PLAYLIST "\xee\x8e\xb1"  // U+e3b1 playlist
#define ICON_IC_PLAYLIST_PLAY "\xee\x8e\xaf"  // U+e3af playlist-play
#define ICON_IC_PLAYLIST_PLUS "\xee\x8e\xb0"  // U+e3b0 playlist-plus
#define ICON_IC_PLAYSTATION_GAMEPAD "\xee\x8e\xb2"  // U+e3b2 playstation-gamepad
#define ICON_IC_PLUG_TYPE_A "\xee\x8e\xb3"  // U+e3b3 plug-type-a
#define ICON_IC_PLUG_TYPE_C "\xee\x8e\xb4"  // U+e3b4 plug-type-c
#define ICON_IC_PLUG_TYPE_G "\xee\x8e\xb5"  // U+e3b5 plug-type-g
#define ICON_IC_PLUG_TYPE_L "\xee\x8e\xb6"  // U+e3b6 plug-type-l
#define ICON_IC_PLUS "\xee\x8e\xba"  // U+e3ba plus
#define ICON_IC_PLUS_CIRCLE "\xee\x8e\xb7"  // U+e3b7 plus-circle
#define ICON_IC_PLUS_SQUARE "\xee\x8e\xb9"  // U+e3b9 plus-square
#define ICON_IC_PLUS_SQUARE_DASHED "\xee\x8e\xb8"  // U+e3b8 plus-square-dashed
#define ICON_IC_PNG_FORMAT "\xee\x8e\xbb"  // U+e3bb png-format
#define ICON_IC_POCKET "\xee\x8e\xbc"  // U+e3bc pocket
#define ICON_IC_PODCAST "\xee\x8e\xbd"  // U+e3bd podcast
#define ICON_IC_POKEBALL "\xee\x8e\xbe"  // U+e3be pokeball
#define ICON_IC_POLAR_SH "\xee\x95\x91"  // U+e551 polar-sh
#define ICON_IC_POSITION "\xee\x8f\x80"  // U+e3c0 position
#define ICON_IC_POSITION_ALIGN "\xee\x8e\xbf"  // U+e3bf position-align
#define ICON_IC_POST "\xee\x8f\x81"  // U+e3c1 post
#define ICON_IC_POTION "\xee\x8f\x82"  // U+e3c2 potion
#define ICON_IC_POUND "\xee\x8f\x83"  // U+e3c3 pound
#define ICON_IC_PRECISION_TOOL "\xee\x8f\x84"  // U+e3c4 precision-tool
#define ICON_IC_PRESENTATION "\xee\x8f\x85"  // U+e3c5 presentation
#define ICON_IC_PRINTER "\xee\x8f\x86"  // U+e3c6 printer
#define ICON_IC_PRINTING_PAGE "\xee\x8f\x87"  // U+e3c7 printing-page
#define ICON_IC_PRIORITY_DOWN "\xee\x8f\x88"  // U+e3c8 priority-down
#define ICON_IC_PRIORITY_HIGH "\xee\x8f\x89"  // U+e3c9 priority-high
#define ICON_IC_PRIORITY_MEDIUM "\xee\x8f\x8a"  // U+e3ca priority-medium
#define ICON_IC_PRIORITY_UP "\xee\x8f\x8b"  // U+e3cb priority-up
#define ICON_IC_PRIVACY_POLICY "\xee\x8f\x8c"  // U+e3cc privacy-policy
#define ICON_IC_PRIVATE_WIFI "\xee\x8f\x8d"  // U+e3cd private-wifi
#define ICON_IC_PROFILE_CIRCLE "\xee\x8f\x8e"  // U+e3ce profile-circle
#define ICON_IC_PROHIBITION "\xee\x8f\x8f"  // U+e3cf prohibition
#define ICON_IC_PROJECT_CURVE_3D "\xee\x8f\x90"  // U+e3d0 project-curve-3d
#define ICON_IC_PUZZLE "\xee\x8f\x91"  // U+e3d1 puzzle
#define ICON_IC_QR_CODE "\xee\x8f\x92"  // U+e3d2 qr-code
#define ICON_IC_QUESTION_MARK "\xee\x8f\x93"  // U+e3d3 question-mark
#define ICON_IC_QUOTE "\xee\x8f\x95"  // U+e3d5 quote
#define ICON_IC_QUOTE_MESSAGE "\xee\x8f\x94"  // U+e3d4 quote-message
#define ICON_IC_RADIATION "\xee\x8f\x96"  // U+e3d6 radiation
#define ICON_IC_RADIUS "\xee\x8f\x97"  // U+e3d7 radius
#define ICON_IC_RAIN "\xee\x8f\x98"  // U+e3d8 rain
#define ICON_IC_RAW_FORMAT "\xee\x8f\x99"  // U+e3d9 raw-format
#define ICON_IC_RECEIVE_DOLLARS "\xee\x8f\x9a"  // U+e3da receive-dollars
#define ICON_IC_RECEIVE_EUROS "\xee\x8f\x9b"  // U+e3db receive-euros
#define ICON_IC_RECEIVE_POUNDS "\xee\x8f\x9c"  // U+e3dc receive-pounds
#define ICON_IC_RECEIVE_YENS "\xee\x8f\x9d"  // U+e3dd receive-yens
#define ICON_IC_REDO "\xee\x8f\xa0"  // U+e3e0 redo
#define ICON_IC_REDO_ACTION "\xee\x8f\x9e"  // U+e3de redo-action
#define ICON_IC_REDO_CIRCLE "\xee\x8f\x9f"  // U+e3df redo-circle
#define ICON_IC_REDUCE "\xee\x8f\xa1"  // U+e3e1 reduce
#define ICON_IC_REFRESH "\xee\x8f\xa4"  // U+e3e4 refresh
#define ICON_IC_REFRESH_CIRCLE "\xee\x8f\xa2"  // U+e3e2 refresh-circle
#define ICON_IC_REFRESH_DOUBLE "\xee\x8f\xa3"  // U+e3e3 refresh-double
#define ICON_IC_RELOAD_WINDOW "\xee\x8f\xa5"  // U+e3e5 reload-window
#define ICON_IC_REMINDER_HAND_GESTURE "\xee\x8f\xa6"  // U+e3e6 reminder-hand-gesture
#define ICON_IC_REPEAT "\xee\x8f\xa8"  // U+e3e8 repeat
#define ICON_IC_REPEAT_ONCE "\xee\x8f\xa7"  // U+e3e7 repeat-once
#define ICON_IC_REPLY "\xee\x8f\xaa"  // U+e3ea reply
#define ICON_IC_REPLY_TO_MESSAGE "\xee\x8f\xa9"  // U+e3e9 reply-to-message
#define ICON_IC_REPORT_COLUMNS "\xee\x8f\xab"  // U+e3eb report-columns
#define ICON_IC_REPORTS "\xee\x8f\xac"  // U+e3ec reports
#define ICON_IC_REPOSITORY "\xee\x8f\xad"  // U+e3ed repository
#define ICON_IC_RESTART "\xee\x8f\xae"  // U+e3ee restart
#define ICON_IC_REWIND "\xee\x8f\xaf"  // U+e3ef rewind
#define ICON_IC_RHOMBUS "\xee\x8f\xb0"  // U+e3f0 rhombus
#define ICON_IC_RHOMBUS_ARROW_RIGHT "\xee\x95\x96"  // U+e556 rhombus-arrow-right
#define ICON_IC_RINGS "\xee\x8f\xb1"  // U+e3f1 rings
#define ICON_IC_ROCKET "\xee\x8f\xb2"  // U+e3f2 rocket
#define ICON_IC_ROOK "\xee\x8f\xb3"  // U+e3f3 rook
#define ICON_IC_ROTATE_CAMERA_LEFT "\xee\x8f\xb4"  // U+e3f4 rotate-camera-left
#define ICON_IC_ROTATE_CAMERA_RIGHT "\xee\x8f\xb5"  // U+e3f5 rotate-camera-right
#define ICON_IC_ROUND_FLASK "\xee\x8f\xb6"  // U+e3f6 round-flask
#define ICON_IC_ROUNDED_MIRROR "\xee\x8f\xb7"  // U+e3f7 rounded-mirror
#define ICON_IC_RSS_FEED "\xee\x8f\xb9"  // U+e3f9 rss-feed
#define ICON_IC_RSS_FEED_TAG "\xee\x8f\xb8"  // U+e3f8 rss-feed-tag
#define ICON_IC_RUBIK_CUBE "\xee\x8f\xba"  // U+e3fa rubik-cube
#define ICON_IC_RULER "\xee\x8f\xbf"  // U+e3ff ruler
#define ICON_IC_RULER_ARROWS "\xee\x8f\xbb"  // U+e3fb ruler-arrows
#define ICON_IC_RULER_COMBINE "\xee\x8f\xbc"  // U+e3fc ruler-combine
#define ICON_IC_RULER_MINUS "\xee\x8f\xbd"  // U+e3fd ruler-minus
#define ICON_IC_RULER_PLUS "\xee\x8f\xbe"  // U+e3fe ruler-plus
#define ICON_IC_RUNNING "\xee\x90\x80"  // U+e400 running
#define ICON_IC_SAFARI "\xee\x90\x81"  // U+e401 safari
#define ICON_IC_SAFE "\xee\x90\x85"  // U+e405 safe
#define ICON_IC_SAFE_ARROW_LEFT "\xee\x90\x82"  // U+e402 safe-arrow-left
#define ICON_IC_SAFE_ARROW_RIGHT "\xee\x90\x83"  // U+e403 safe-arrow-right
#define ICON_IC_SAFE_OPEN "\xee\x90\x84"  // U+e404 safe-open
#define ICON_IC_SANDALS "\xee\x90\x86"  // U+e406 sandals
#define ICON_IC_SCALE_FRAME_ENLARGE "\xee\x90\x87"  // U+e407 scale-frame-enlarge
#define ICON_IC_SCALE_FRAME_REDUCE "\xee\x90\x88"  // U+e408 scale-frame-reduce
#define ICON_IC_SCAN_BARCODE "\xee\x90\x89"  // U+e409 scan-barcode
#define ICON_IC_SCAN_QR_CODE "\xee\x90\x8a"  // U+e40a scan-qr-code
#define ICON_IC_SCANNING "\xee\x90\x8b"  // U+e40b scanning
#define ICON_IC_SCARF "\xee\x90\x8c"  // U+e40c scarf
#define ICON_IC_SCISSOR "\xee\x90\x8e"  // U+e40e scissor
#define ICON_IC_SCISSOR_ALT "\xee\x90\x8d"  // U+e40d scissor-alt
#define ICON_IC_SCREENSHOT "\xee\x90\x8f"  // U+e40f screenshot
#define ICON_IC_SEA_AND_SUN "\xee\x90\x90"  // U+e410 sea-and-sun
#define ICON_IC_SEA_WAVES "\xee\x90\x91"  // U+e411 sea-waves
#define ICON_IC_SEARCH "\xee\x90\x94"  // U+e414 search
#define ICON_IC_SEARCH_ENGINE "\xee\x90\x92"  // U+e412 search-engine
#define ICON_IC_SEARCH_WINDOW "\xee\x90\x93"  // U+e413 search-window
#define ICON_IC_SECURE_WINDOW "\xee\x90\x95"  // U+e415 secure-window
#define ICON_IC_SECURITY_PASS "\xee\x90\x96"  // U+e416 security-pass
#define ICON_IC_SELECT_EDGE_3D "\xee\x90\x97"  // U+e417 select-edge-3d
#define ICON_IC_SELECT_FACE_3D "\xee\x90\x98"  // U+e418 select-face-3d
#define ICON_IC_SELECT_POINT_3D "\xee\x90\x99"  // U+e419 select-point-3d
#define ICON_IC_SELECT_WINDOW "\xee\x90\x9a"  // U+e41a select-window
#define ICON_IC_SELECTIVE_TOOL "\xee\x90\x9b"  // U+e41b selective-tool
#define ICON_IC_SEND "\xee\x90\xa2"  // U+e422 send
#define ICON_IC_SEND_DIAGONAL "\xee\x90\x9c"  // U+e41c send-diagonal
#define ICON_IC_SEND_DOLLARS "\xee\x90\x9d"  // U+e41d send-dollars
#define ICON_IC_SEND_EUROS "\xee\x90\x9e"  // U+e41e send-euros
#define ICON_IC_SEND_MAIL "\xee\x90\x9f"  // U+e41f send-mail
#define ICON_IC_SEND_POUNDS "\xee\x90\xa0"  // U+e420 send-pounds
#define ICON_IC_SEND_YENS "\xee\x90\xa1"  // U+e421 send-yens
#define ICON_IC_SERVER "\xee\x90\xa4"  // U+e424 server
#define ICON_IC_SERVER_CONNECTION "\xee\x90\xa3"  // U+e423 server-connection
#define ICON_IC_SETTINGS "\xee\x90\xa6"  // U+e426 settings
#define ICON_IC_SETTINGS_PROFILES "\xee\x90\xa5"  // U+e425 settings-profiles
#define ICON_IC_SHARE_ANDROID "\xee\x90\xa7"  // U+e427 share-android
#define ICON_IC_SHARE_IOS "\xee\x90\xa8"  // U+e428 share-ios
#define ICON_IC_SHIELD "\xee\x90\xb6"  // U+e436 shield
#define ICON_IC_SHIELD_ALERT "\xee\x90\xa9"  // U+e429 shield-alert
#define ICON_IC_SHIELD_ALT "\xee\x90\xaa"  // U+e42a shield-alt
#define ICON_IC_SHIELD_BROKEN "\xee\x90\xab"  // U+e42b shield-broken
#define ICON_IC_SHIELD_CHECK "\xee\x90\xac"  // U+e42c shield-check
#define ICON_IC_SHIELD_DOWNLOAD "\xee\x90\xad"  // U+e42d shield-download
#define ICON_IC_SHIELD_EYE "\xee\x90\xae"  // U+e42e shield-eye
#define ICON_IC_SHIELD_LOADING "\xee\x90\xaf"  // U+e42f shield-loading
#define ICON_IC_SHIELD_MINUS "\xee\x90\xb0"  // U+e430 shield-minus
#define ICON_IC_SHIELD_PLUS_IN "\xee\x90\xb1"  // U+e431 shield-plus-in
#define ICON_IC_SHIELD_QUESTION "\xee\x90\xb2"  // U+e432 shield-question
#define ICON_IC_SHIELD_SEARCH "\xee\x90\xb3"  // U+e433 shield-search
#define ICON_IC_SHIELD_UPLOAD "\xee\x90\xb4"  // U+e434 shield-upload
#define ICON_IC_SHIELD_XMARK "\xee\x90\xb5"  // U+e435 shield-xmark
#define ICON_IC_SHIRT "\xee\x90\xb8"  // U+e438 shirt
#define ICON_IC_SHIRT_TANK_TOP "\xee\x90\xb7"  // U+e437 shirt-tank-top
#define ICON_IC_SHOP "\xee\x90\xbc"  // U+e43c shop
#define ICON_IC_SHOP_FOUR_TILES "\xee\x90\xba"  // U+e43a shop-four-tiles
#define ICON_IC_SHOP_FOUR_TILES_WINDOW "\xee\x90\xb9"  // U+e439 shop-four-tiles-window
#define ICON_IC_SHOP_WINDOW "\xee\x90\xbb"  // U+e43b shop-window
#define ICON_IC_SHOPPING_BAG "\xee\x91\x84"  // U+e444 shopping-bag
#define ICON_IC_SHOPPING_BAG_ARROW_DOWN "\xee\x90\xbd"  // U+e43d shopping-bag-arrow-down
#define ICON_IC_SHOPPING_BAG_ARROW_UP "\xee\x90\xbe"  // U+e43e shopping-bag-arrow-up
#define ICON_IC_SHOPPING_BAG_CHECK "\xee\x90\xbf"  // U+e43f shopping-bag-check
#define ICON_IC_SHOPPING_BAG_MINUS "\xee\x91\x80"  // U+e440 shopping-bag-minus
#define ICON_IC_SHOPPING_BAG_PLUS "\xee\x91\x81"  // U+e441 shopping-bag-plus
#define ICON_IC_SHOPPING_BAG_POCKET "\xee\x91\x82"  // U+e442 shopping-bag-pocket
#define ICON_IC_SHOPPING_BAG_WARNING "\xee\x91\x83"  // U+e443 shopping-bag-warning
#define ICON_IC_SHOPPING_CODE "\xee\x91\x87"  // U+e447 shopping-code
#define ICON_IC_SHOPPING_CODE_CHECK "\xee\x91\x85"  // U+e445 shopping-code-check
#define ICON_IC_SHOPPING_CODE_XMARK "\xee\x91\x86"  // U+e446 shopping-code-xmark
#define ICON_IC_SHORT_PANTS "\xee\x91\x89"  // U+e449 short-pants
#define ICON_IC_SHORT_PANTS_POCKETS "\xee\x91\x88"  // U+e448 short-pants-pockets
#define ICON_IC_SHORTCUT_SQUARE "\xee\x91\x8a"  // U+e44a shortcut-square
#define ICON_IC_SHUFFLE "\xee\x91\x8b"  // U+e44b shuffle
#define ICON_IC_SIDEBAR_COLLAPSE "\xee\x91\x8c"  // U+e44c sidebar-collapse
#define ICON_IC_SIDEBAR_EXPAND "\xee\x91\x8d"  // U+e44d sidebar-expand
#define ICON_IC_SIGMA_FUNCTION "\xee\x91\x8e"  // U+e44e sigma-function
#define ICON_IC_SIMPLE_CART "\xee\x91\x8f"  // U+e44f simple-cart
#define ICON_IC_SINE_WAVE "\xee\x91\x90"  // U+e450 sine-wave
#define ICON_IC_SINGLE_TAP_GESTURE "\xee\x91\x91"  // U+e451 single-tap-gesture
#define ICON_IC_SKATEBOARD "\xee\x91\x92"  // U+e452 skateboard
#define ICON_IC_SKATEBOARDING "\xee\x91\x93"  // U+e453 skateboarding
#define ICON_IC_SKIP_NEXT "\xee\x91\x94"  // U+e454 skip-next
#define ICON_IC_SKIP_PREV "\xee\x91\x95"  // U+e455 skip-prev
#define ICON_IC_SLASH "\xee\x91\x97"  // U+e457 slash
#define ICON_IC_SLASH_SQUARE "\xee\x91\x96"  // U+e456 slash-square
#define ICON_IC_SLEEPER_CHAIR "\xee\x91\x98"  // U+e458 sleeper-chair
#define ICON_IC_SLIPS "\xee\x91\x99"  // U+e459 slips
#define ICON_IC_SMALL_LAMP "\xee\x91\x9b"  // U+e45b small-lamp
#define ICON_IC_SMALL_LAMP_ALT "\xee\x91\x9a"  // U+e45a small-lamp-alt
#define ICON_IC_SMARTPHONE_DEVICE "\xee\x91\x9c"  // U+e45c smartphone-device
#define ICON_IC_SMOKING "\xee\x91\x9d"  // U+e45d smoking
#define ICON_IC_SNAPCHAT "\xee\x91\x9e"  // U+e45e snapchat
#define ICON_IC_SNOW "\xee\x91\xa0"  // U+e460 snow
#define ICON_IC_SNOW_FLAKE "\xee\x91\x9f"  // U+e45f snow-flake
#define ICON_IC_SOAP "\xee\x91\xa1"  // U+e461 soap
#define ICON_IC_SOCCER_BALL "\xee\x91\xa2"  // U+e462 soccer-ball
#define ICON_IC_SOFA "\xee\x91\xa3"  // U+e463 sofa
#define ICON_IC_SOIL "\xee\x91\xa5"  // U+e465 soil
#define ICON_IC_SOIL_ALT "\xee\x91\xa4"  // U+e464 soil-alt
#define ICON_IC_SORT "\xee\x91\xa8"  // U+e468 sort
#define ICON_IC_SORT_DOWN "\xee\x91\xa6"  // U+e466 sort-down
#define ICON_IC_SORT_UP "\xee\x91\xa7"  // U+e467 sort-up
#define ICON_IC_SOUND_HIGH "\xee\x91\xa9"  // U+e469 sound-high
#define ICON_IC_SOUND_LOW "\xee\x91\xaa"  // U+e46a sound-low
#define ICON_IC_SOUND_MIN "\xee\x91\xab"  // U+e46b sound-min
#define ICON_IC_SOUND_OFF "\xee\x91\xac"  // U+e46c sound-off
#define ICON_IC_SPADES "\xee\x91\xad"  // U+e46d spades
#define ICON_IC_SPARK "\xee\x91\xae"  // U+e46e spark
#define ICON_IC_SPARKS "\xee\x91\xaf"  // U+e46f sparks
#define ICON_IC_SPHERE "\xee\x91\xb0"  // U+e470 sphere
#define ICON_IC_SPIRAL "\xee\x91\xb1"  // U+e471 spiral
#define ICON_IC_SPLIT_AREA "\xee\x91\xb2"  // U+e472 split-area
#define ICON_IC_SPLIT_SQUARE_DASHED "\xee\x91\xb3"  // U+e473 split-square-dashed
#define ICON_IC_SPOCK_HAND_GESTURE "\xee\x91\xb4"  // U+e474 spock-hand-gesture
#define ICON_IC_SPOTIFY "\xee\x91\xb5"  // U+e475 spotify
#define ICON_IC_SQUARE "\xee\x91\xbc"  // U+e47c square
#define ICON_IC_SQUARE_3D_CORNER_TO_CORNER "\xee\x91\xb6"  // U+e476 square-3d-corner-to-corner
#define ICON_IC_SQUARE_3D_FROM_CENTER "\xee\x91\xb7"  // U+e477 square-3d-from-center
#define ICON_IC_SQUARE_3D_THREE_POINTS "\xee\x91\xb8"  // U+e478 square-3d-three-points
#define ICON_IC_SQUARE_CURSOR "\xee\x91\xb9"  // U+e479 square-cursor
#define ICON_IC_SQUARE_DASHED "\xee\x91\xba"  // U+e47a square-dashed
#define ICON_IC_SQUARE_WAVE "\xee\x91\xbb"  // U+e47b square-wave
#define ICON_IC_STACKOVERFLOW "\xee\x91\xbd"  // U+e47d stackoverflow
#define ICON_IC_STAR "\xee\x92\x80"  // U+e480 star
#define ICON_IC_STAR_DASHED "\xee\x91\xbe"  // U+e47e star-dashed
#define ICON_IC_STAR_HALF_DASHED "\xee\x91\xbf"  // U+e47f star-half-dashed
#define ICON_IC_STAT_DOWN "\xee\x92\x81"  // U+e481 stat-down
#define ICON_IC_STAT_UP "\xee\x92\x82"  // U+e482 stat-up
#define ICON_IC_STATS_DOWN_SQUARE "\xee\x92\x83"  // U+e483 stats-down-square
#define ICON_IC_STATS_REPORT "\xee\x92\x84"  // U+e484 stats-report
#define ICON_IC_STATS_UP_SQUARE "\xee\x92\x85"  // U+e485 stats-up-square
#define ICON_IC_STRATEGY "\xee\x92\x86"  // U+e486 strategy
#define ICON_IC_STRETCHING "\xee\x92\x87"  // U+e487 stretching
#define ICON_IC_STRIKETHROUGH "\xee\x92\x88"  // U+e488 strikethrough
#define ICON_IC_STROLLER "\xee\x92\x89"  // U+e489 stroller
#define ICON_IC_STYLE_BORDER "\xee\x92\x8a"  // U+e48a style-border
#define ICON_IC_SUBMIT_DOCUMENT "\xee\x92\x8b"  // U+e48b submit-document
#define ICON_IC_SUBSTRACT "\xee\x92\x8c"  // U+e48c substract
#define ICON_IC_SUGGESTION "\xee\x92\x8d"  // U+e48d suggestion
#define ICON_IC_SUITCASE "\xee\x92\x8e"  // U+e48e suitcase
#define ICON_IC_SUN_LIGHT "\xee\x92\x8f"  // U+e48f sun-light
#define ICON_IC_SVG_FORMAT "\xee\x92\x90"  // U+e490 svg-format
#define ICON_IC_SWEEP_3D "\xee\x92\x91"  // U+e491 sweep-3d
#define ICON_IC_SWIMMING "\xee\x92\x92"  // U+e492 swimming
#define ICON_IC_SWIPE_DOWN_GESTURE "\xee\x92\x93"  // U+e493 swipe-down-gesture
#define ICON_IC_SWIPE_LEFT_GESTURE "\xee\x92\x94"  // U+e494 swipe-left-gesture
#define ICON_IC_SWIPE_RIGHT_GESTURE "\xee\x92\x95"  // U+e495 swipe-right-gesture
#define ICON_IC_SWIPE_TWO_FINGERS_DOWN_GESTURE "\xee\x92\x96"  // U+e496 swipe-two-fingers-down-gesture
#define ICON_IC_SWIPE_TWO_FINGERS_LEFT_GESTURE "\xee\x92\x97"  // U+e497 swipe-two-fingers-left-gesture
#define ICON_IC_SWIPE_TWO_FINGERS_RIGHT_GESTURE "\xee\x92\x98"  // U+e498 swipe-two-fingers-right-gesture
#define ICON_IC_SWIPE_TWO_FINGERS_UP_GESTURE "\xee\x92\x99"  // U+e499 swipe-two-fingers-up-gesture
#define ICON_IC_SWIPE_UP_GESTURE "\xee\x92\x9a"  // U+e49a swipe-up-gesture
#define ICON_IC_SWITCH_OFF "\xee\x92\x9b"  // U+e49b switch-off
#define ICON_IC_SWITCH_ON "\xee\x92\x9c"  // U+e49c switch-on
#define ICON_IC_SYSTEM_RESTART "\xee\x92\x9d"  // U+e49d system-restart
#define ICON_IC_SYSTEM_SHUT "\xee\x92\x9e"  // U+e49e system-shut
#define ICON_IC_TABLE "\xee\x92\xa1"  // U+e4a1 table
#define ICON_IC_TABLE_2_COLUMNS "\xee\x92\x9f"  // U+e49f table-2-columns
#define ICON_IC_TABLE_ROWS "\xee\x92\xa0"  // U+e4a0 table-rows
#define ICON_IC_TASK_LIST "\xee\x92\xa2"  // U+e4a2 task-list
#define ICON_IC_TELEGRAM "\xee\x92\xa4"  // U+e4a4 telegram
#define ICON_IC_TELEGRAM_CIRCLE "\xee\x92\xa3"  // U+e4a3 telegram-circle
#define ICON_IC_TEMPERATURE_DOWN "\xee\x92\xa5"  // U+e4a5 temperature-down
#define ICON_IC_TEMPERATURE_HIGH "\xee\x92\xa6"  // U+e4a6 temperature-high
#define ICON_IC_TEMPERATURE_LOW "\xee\x92\xa7"  // U+e4a7 temperature-low
#define ICON_IC_TEMPERATURE_UP "\xee\x92\xa8"  // U+e4a8 temperature-up
#define ICON_IC_TENNIS_BALL "\xee\x92\xaa"  // U+e4aa tennis-ball
#define ICON_IC_TENNIS_BALL_ALT "\xee\x92\xa9"  // U+e4a9 tennis-ball-alt
#define ICON_IC_TERMINAL "\xee\x92\xac"  // U+e4ac terminal
#define ICON_IC_TERMINAL_TAG "\xee\x92\xab"  // U+e4ab terminal-tag
#define ICON_IC_TEST_TUBE "\xee\x92\xad"  // U+e4ad test-tube
#define ICON_IC_TEXT "\xee\x92\xb3"  // U+e4b3 text
#define ICON_IC_TEXT_ARROWS_UP_DOWN "\xee\x92\xae"  // U+e4ae text-arrows-up-down
#define ICON_IC_TEXT_BOX "\xee\x92\xaf"  // U+e4af text-box
#define ICON_IC_TEXT_MAGNIFYING_GLASS "\xee\x92\xb0"  // U+e4b0 text-magnifying-glass
#define ICON_IC_TEXT_SIZE "\xee\x92\xb1"  // U+e4b1 text-size
#define ICON_IC_TEXT_SQUARE "\xee\x92\xb2"  // U+e4b2 text-square
#define ICON_IC_THREADS "\xee\x92\xb4"  // U+e4b4 threads
#define ICON_IC_THREE_POINTS_CIRCLE "\xee\x92\xb5"  // U+e4b5 three-points-circle
#define ICON_IC_THREE_STARS "\xee\x92\xb6"  // U+e4b6 three-stars
#define ICON_IC_THUMBS_DOWN "\xee\x92\xb7"  // U+e4b7 thumbs-down
#define ICON_IC_THUMBS_UP "\xee\x92\xb8"  // U+e4b8 thumbs-up
#define ICON_IC_THUNDERSTORM "\xee\x92\xb9"  // U+e4b9 thunderstorm
#define ICON_IC_TIF_FORMAT "\xee\x92\xba"  // U+e4ba tif-format
#define ICON_IC_TIFF_FORMAT "\xee\x92\xbb"  // U+e4bb tiff-format
#define ICON_IC_TIKTOK "\xee\x92\xbc"  // U+e4bc tiktok
#define ICON_IC_TIME_ZONE "\xee\x92\xbd"  // U+e4bd time-zone
#define ICON_IC_TIMER "\xee\x92\xbf"  // U+e4bf timer
#define ICON_IC_TIMER_OFF "\xee\x92\xbe"  // U+e4be timer-off
#define ICON_IC_TOOLS "\xee\x93\x80"  // U+e4c0 tools
#define ICON_IC_TOURNAMENT "\xee\x93\x81"  // U+e4c1 tournament
#define ICON_IC_TOWER "\xee\x93\x85"  // U+e4c5 tower
#define ICON_IC_TOWER_CHECK "\xee\x93\x82"  // U+e4c2 tower-check
#define ICON_IC_TOWER_NO_ACCESS "\xee\x93\x83"  // U+e4c3 tower-no-access
#define ICON_IC_TOWER_WARNING "\xee\x93\x84"  // U+e4c4 tower-warning
#define ICON_IC_TRADEMARK "\xee\x93\x86"  // U+e4c6 trademark
#define ICON_IC_TRAIN "\xee\x93\x87"  // U+e4c7 train
#define ICON_IC_TRAM "\xee\x93\x88"  // U+e4c8 tram
#define ICON_IC_TRANSITION_DOWN "\xee\x93\x89"  // U+e4c9 transition-down
#define ICON_IC_TRANSITION_LEFT "\xee\x93\x8a"  // U+e4ca transition-left
#define ICON_IC_TRANSITION_RIGHT "\xee\x93\x8b"  // U+e4cb transition-right
#define ICON_IC_TRANSITION_UP "\xee\x93\x8c"  // U+e4cc transition-up
#define ICON_IC_TRANSLATE "\xee\x93\x8d"  // U+e4cd translate
#define ICON_IC_TRASH "\xee\x93\x8e"  // U+e4ce trash
#define ICON_IC_TREADMILL "\xee\x93\x8f"  // U+e4cf treadmill
#define ICON_IC_TREE "\xee\x93\x90"  // U+e4d0 tree
#define ICON_IC_TREKKING "\xee\x93\x91"  // U+e4d1 trekking
#define ICON_IC_TRELLO "\xee\x93\x92"  // U+e4d2 trello
#define ICON_IC_TRIANGLE "\xee\x93\x96"  // U+e4d6 triangle
#define ICON_IC_TRIANGLE_FLAG "\xee\x93\x95"  // U+e4d5 triangle-flag
#define ICON_IC_TRIANGLE_FLAG_CIRCLE "\xee\x93\x93"  // U+e4d3 triangle-flag-circle
#define ICON_IC_TRIANGLE_FLAG_TWO_STRIPES "\xee\x93\x94"  // U+e4d4 triangle-flag-two-stripes
#define ICON_IC_TROPHY "\xee\x93\x97"  // U+e4d7 trophy
#define ICON_IC_TRUCK "\xee\x93\x9a"  // U+e4da truck
#define ICON_IC_TRUCK_GREEN "\xee\x93\x98"  // U+e4d8 truck-green
#define ICON_IC_TRUCK_LENGTH "\xee\x93\x99"  // U+e4d9 truck-length
#define ICON_IC_TUNNEL "\xee\x93\x9b"  // U+e4db tunnel
#define ICON_IC_TV "\xee\x93\x9e"  // U+e4de tv
#define ICON_IC_TV_FIX "\xee\x93\x9c"  // U+e4dc tv-fix
#define ICON_IC_TV_WARNING "\xee\x93\x9d"  // U+e4dd tv-warning
#define ICON_IC_TWITTER "\xee\x93\x9f"  // U+e4df twitter
#define ICON_IC_TWO_POINTS_CIRCLE "\xee\x93\xa0"  // U+e4e0 two-points-circle
#define ICON_IC_TWO_SEATER_SOFA "\xee\x93\xa1"  // U+e4e1 two-seater-sofa
#define ICON_IC_TYPE "\xee\x93\xa2"  // U+e4e2 type
#define ICON_IC_U_TURN_ARROW_LEFT "\xee\x95\x97"  // U+e557 u-turn-arrow-left
#define ICON_IC_U_TURN_ARROW_RIGHT "\xee\x95\x98"  // U+e558 u-turn-arrow-right
#define ICON_IC_UMBRELLA "\xee\x93\xa3"  // U+e4e3 umbrella
#define ICON_IC_UNDERLINE "\xee\x93\xa5"  // U+e4e5 underline
#define ICON_IC_UNDERLINE_SQUARE "\xee\x93\xa4"  // U+e4e4 underline-square
#define ICON_IC_UNDO "\xee\x93\xa8"  // U+e4e8 undo
#define ICON_IC_UNDO_ACTION "\xee\x93\xa6"  // U+e4e6 undo-action
#define ICON_IC_UNDO_CIRCLE "\xee\x93\xa7"  // U+e4e7 undo-circle
#define ICON_IC_UNION "\xee\x93\xab"  // U+e4eb union
#define ICON_IC_UNION_ALT "\xee\x93\xa9"  // U+e4e9 union-alt
#define ICON_IC_UNION_HORIZ_ALT "\xee\x93\xaa"  // U+e4ea union-horiz-alt
#define ICON_IC_UNITY "\xee\x93\xad"  // U+e4ed unity
#define ICON_IC_UNITY_5 "\xee\x93\xac"  // U+e4ec unity-5
#define ICON_IC_UNJOIN_3D "\xee\x93\xae"  // U+e4ee unjoin-3d
#define ICON_IC_UO_FOLDER_USER "\xee\x95\xa4"  // U+e564 uo-folder-user
#define ICON_IC_UO_USER_SETTINGS "\xee\x95\x9c"  // U+e55c uo-user-settings
#define ICON_IC_UPLOAD "\xee\x93\xb1"  // U+e4f1 upload
#define ICON_IC_UPLOAD_DATA_WINDOW "\xee\x93\xaf"  // U+e4ef upload-data-window
#define ICON_IC_UPLOAD_SQUARE "\xee\x93\xb0"  // U+e4f0 upload-square
#define ICON_IC_USB "\xee\x93\xb2"  // U+e4f2 usb
#define ICON_IC_USER "\xee\x93\xbe"  // U+e4fe user
#define ICON_IC_USER_BADGE_CHECK "\xee\x93\xb3"  // U+e4f3 user-badge-check
#define ICON_IC_USER_BAG "\xee\x93\xb4"  // U+e4f4 user-bag
#define ICON_IC_USER_CART "\xee\x93\xb5"  // U+e4f5 user-cart
#define ICON_IC_USER_CIRCLE "\xee\x93\xb6"  // U+e4f6 user-circle
#define ICON_IC_USER_CROWN "\xee\x93\xb7"  // U+e4f7 user-crown
#define ICON_IC_USER_LOVE "\xee\x93\xb8"  // U+e4f8 user-love
#define ICON_IC_USER_PLUS "\xee\x93\xb9"  // U+e4f9 user-plus
#define ICON_IC_USER_SCAN "\xee\x93\xba"  // U+e4fa user-scan
#define ICON_IC_USER_SQUARE "\xee\x93\xbb"  // U+e4fb user-square
#define ICON_IC_USER_STAR "\xee\x93\xbc"  // U+e4fc user-star
#define ICON_IC_USER_XMARK "\xee\x93\xbd"  // U+e4fd user-xmark
#define ICON_IC_VEGAN "\xee\x94\x81"  // U+e501 vegan
#define ICON_IC_VEGAN_CIRCLE "\xee\x93\xbf"  // U+e4ff vegan-circle
#define ICON_IC_VEGAN_SQUARE "\xee\x94\x80"  // U+e500 vegan-square
#define ICON_IC_VEHICLE_GREEN "\xee\x94\x82"  // U+e502 vehicle-green
#define ICON_IC_VERTICAL_MERGE "\xee\x94\x83"  // U+e503 vertical-merge
#define ICON_IC_VERTICAL_SPLIT "\xee\x94\x84"  // U+e504 vertical-split
#define ICON_IC_VIALS "\xee\x94\x85"  // U+e505 vials
#define ICON_IC_VIDEO_CAMERA "\xee\x94\x87"  // U+e507 video-camera
#define ICON_IC_VIDEO_CAMERA_OFF "\xee\x94\x86"  // U+e506 video-camera-off
#define ICON_IC_VIDEO_PROJECTOR "\xee\x94\x88"  // U+e508 video-projector
#define ICON_IC_VIEW_360 "\xee\x94\x89"  // U+e509 view-360
#define ICON_IC_VIEW_COLUMNS_2 "\xee\x94\x8a"  // U+e50a view-columns-2
#define ICON_IC_VIEW_COLUMNS_3 "\xee\x94\x8b"  // U+e50b view-columns-3
#define ICON_IC_VIEW_GRID "\xee\x94\x8c"  // U+e50c view-grid
#define ICON_IC_VIEW_STRUCTURE_DOWN "\xee\x94\x8d"  // U+e50d view-structure-down
#define ICON_IC_VIEW_STRUCTURE_UP "\xee\x94\x8e"  // U+e50e view-structure-up
#define ICON_IC_VOICE "\xee\x94\x95"  // U+e515 voice
#define ICON_IC_VOICE_CHECK "\xee\x94\x8f"  // U+e50f voice-check
#define ICON_IC_VOICE_CIRCLE "\xee\x94\x90"  // U+e510 voice-circle
#define ICON_IC_VOICE_LOCK_CIRCLE "\xee\x94\x91"  // U+e511 voice-lock-circle
#define ICON_IC_VOICE_SCAN "\xee\x94\x92"  // U+e512 voice-scan
#define ICON_IC_VOICE_SQUARE "\xee\x94\x93"  // U+e513 voice-square
#define ICON_IC_VOICE_XMARK "\xee\x94\x94"  // U+e514 voice-xmark
#define ICON_IC_VR_TAG "\xee\x94\x96"  // U+e516 vr-tag
#define ICON_IC_VUE_JS "\xee\x94\x97"  // U+e517 vue-js
#define ICON_IC_WAIST "\xee\x94\x98"  // U+e518 waist
#define ICON_IC_WALKING "\xee\x94\x99"  // U+e519 walking
#define ICON_IC_WALLET "\xee\x94\x9a"  // U+e51a wallet
#define ICON_IC_WARNING_CIRCLE "\xee\x94\x9b"  // U+e51b warning-circle
#define ICON_IC_WARNING_HEXAGON "\xee\x94\x9c"  // U+e51c warning-hexagon
#define ICON_IC_WARNING_SQUARE "\xee\x94\x9d"  // U+e51d warning-square
#define ICON_IC_WARNING_TRIANGLE "\xee\x94\x9e"  // U+e51e warning-triangle
#define ICON_IC_WARNING_WINDOW "\xee\x94\x9f"  // U+e51f warning-window
#define ICON_IC_WASH "\xee\x94\xa0"  // U+e520 wash
#define ICON_IC_WASHING_MACHINE "\xee\x94\xa1"  // U+e521 washing-machine
#define ICON_IC_WATERING_SOIL "\xee\x94\xa2"  // U+e522 watering-soil
#define ICON_IC_WEB_WINDOW "\xee\x94\xa5"  // U+e525 web-window
#define ICON_IC_WEB_WINDOW_ENERGY_CONSUMPTION "\xee\x94\xa3"  // U+e523 web-window-energy-consumption
#define ICON_IC_WEB_WINDOW_XMARK "\xee\x94\xa4"  // U+e524 web-window-xmark
#define ICON_IC_WEBP_FORMAT "\xee\x94\xa6"  // U+e526 webp-format
#define ICON_IC_WEIGHT "\xee\x94\xa8"  // U+e528 weight
#define ICON_IC_WEIGHT_ALT "\xee\x94\xa7"  // U+e527 weight-alt
#define ICON_IC_WHATSAPP "\xee\x95\xa8"  // U+e568 whatsapp
#define ICON_IC_WHITE_FLAG "\xee\x94\xa9"  // U+e529 white-flag
#define ICON_IC_WIFI "\xee\x94\xaf"  // U+e52f wifi
#define ICON_IC_WIFI_OFF "\xee\x94\xaa"  // U+e52a wifi-off
#define ICON_IC_WIFI_SIGNAL_NONE "\xee\x94\xab"  // U+e52b wifi-signal-none
#define ICON_IC_WIFI_TAG "\xee\x94\xac"  // U+e52c wifi-tag
#define ICON_IC_WIFI_WARNING "\xee\x94\xad"  // U+e52d wifi-warning
#define ICON_IC_WIFI_XMARK "\xee\x94\xae"  // U+e52e wifi-xmark
#define ICON_IC_WIND "\xee\x94\xb0"  // U+e530 wind
#define ICON_IC_WINDOW_CHECK "\xee\x94\xb1"  // U+e531 window-check
#define ICON_IC_WINDOW_LOCK "\xee\x94\xb2"  // U+e532 window-lock
#define ICON_IC_WINDOW_NO_ACCESS "\xee\x94\xb3"  // U+e533 window-no-access
#define ICON_IC_WINDOW_TABS "\xee\x95\x9a"  // U+e55a window-tabs
#define ICON_IC_WINDOW_XMARK "\xee\x94\xb4"  // U+e534 window-xmark
#define ICON_IC_WINDOWS "\xee\x94\xb5"  // U+e535 windows
#define ICON_IC_WOLF "\xee\x94\xb6"  // U+e536 wolf
#define ICON_IC_WRAP_TEXT "\xee\x94\xb7"  // U+e537 wrap-text
#define ICON_IC_WRENCH "\xee\x94\xb8"  // U+e538 wrench
#define ICON_IC_WRISTWATCH "\xee\x94\xb9"  // U+e539 wristwatch
#define ICON_IC_WWW "\xee\x94\xba"  // U+e53a www
#define ICON_IC_X "\xee\x95\x92"  // U+e552 x
#define ICON_IC_X_SQUARE "\xee\x94\xbb"  // U+e53b x-square
#define ICON_IC_XBOX_A "\xee\x94\xbc"  // U+e53c xbox-a
#define ICON_IC_XBOX_B "\xee\x94\xbd"  // U+e53d xbox-b
#define ICON_IC_XBOX_X "\xee\x94\xbe"  // U+e53e xbox-x
#define ICON_IC_XBOX_Y "\xee\x94\xbf"  // U+e53f xbox-y
#define ICON_IC_XMARK "\xee\x95\x82"  // U+e542 xmark
#define ICON_IC_XMARK_CIRCLE "\xee\x95\x80"  // U+e540 xmark-circle
#define ICON_IC_XMARK_SQUARE "\xee\x95\x81"  // U+e541 xmark-square
#define ICON_IC_XRAY_VIEW "\xee\x95\x83"  // U+e543 xray-view
#define ICON_IC_Y_SQUARE "\xee\x95\x84"  // U+e544 y-square
#define ICON_IC_YELP "\xee\x95\x85"  // U+e545 yelp
#define ICON_IC_YEN "\xee\x95\x87"  // U+e547 yen
#define ICON_IC_YEN_SQUARE "\xee\x95\x86"  // U+e546 yen-square
#define ICON_IC_YOGA "\xee\x95\x88"  // U+e548 yoga
#define ICON_IC_YOUTUBE "\xee\x95\x89"  // U+e549 youtube
#define ICON_IC_Z_SQUARE "\xee\x95\x8a"  // U+e54a z-square
#define ICON_IC_ZOOM_IN "\xee\x95\x8b"  // U+e54b zoom-in
#define ICON_IC_ZOOM_OUT "\xee\x95\x8c"  // U+e54c zoom-out
