#pragma once
// Generation-map lineage - the raw material of general ("gen") topological
// naming, and the seed of full coverage for op-GENERATED sub-shapes (fillet
// blends, boolean seams, loft/revolve surfaces) that no sketch scheme can name.
//
// Every modeling operation, when it builds geometry with an OCCT
// BRepBuilderAPI_MakeShape, can report how each OUTPUT sub-shape derives from
// the INPUT via Generated()/Modified()/IsDeleted(). A GenerationLedger records
// that derivation for one op execution. A sub-shape named by its derivation
// ("the face generated by input-edge X") is STABLE across a parameter edit,
// because the derivation STRUCTURE doesn't change even when the geometry moves
// - which is exactly what geometric matching can't guarantee.
//
// The op populates a ledger on every (re)execute; topo::Context carries a
// pointer to the current one, so the "gen" strategy (TopoName.cpp) can mint and
// resolve names through it. Wiring each production op to publish its maps is an
// additive follow-on; this defines the shared vocabulary.

#include <TopoDS_Shape.hxx>
#include <TopAbs_ShapeEnum.hxx>
#include <TopTools_IndexedDataMapOfShapeListOfShape.hxx>
#include <Standard_Handle.hxx>
#include <vector>

class BRepBuilderAPI_MakeShape;
class BRepTools_History;

namespace materializr {
namespace topo {

struct GenerationLedger {
    // The op's input shape(s). One for extrude/fillet/chamfer; a BOOLEAN has
    // TWO (target + tool) - a seam edge derives from a face of each. The gen
    // strategy names an input sub-shape against WHICHEVER input it belongs to.
    struct Input {
        TopoDS_Shape     shape;
        TopAbs_ShapeEnum type = TopAbs_EDGE;  // sub-shape type tracked
    };
    std::vector<Input> inputs;
    // input sub-shape -> the output sub-shapes it produced (keys from any input).
    TopTools_IndexedDataMapOfShapeListOfShape generated;
    TopTools_IndexedDataMapOfShapeListOfShape modified;

    // Back-compat single-input view (extrude/fillet/chamfer callers).
    const TopoDS_Shape& firstInput() const {
        static const TopoDS_Shape kNull;
        return inputs.empty() ? kNull : inputs.front().shape;
    }

    // Capture from any builder: for each sub-shape of `in` of type `t`, record
    // what it Generated / was Modified into. Clears any prior contents.
    void capture(BRepBuilderAPI_MakeShape& mk, const TopoDS_Shape& in,
                 TopAbs_ShapeEnum t);
    // Append another input's maps WITHOUT clearing (booleans call capture for
    // the target then captureAdd for the tool).
    void captureAdd(BRepBuilderAPI_MakeShape& mk, const TopoDS_Shape& in,
                    TopAbs_ShapeEnum t);
    // Which input does this sub-shape belong to? -1 if none.
    int inputOf(const TopoDS_Shape& sub) const;
};

} // namespace topo
} // namespace materializr
